"""Part 2: CH02 and CH03 question data for gen-maogai-quiz-ch01-03.py"""

CH02 = [
    {
        "id": "q001", "type": "single_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 二、六届六中全会与《论新阶段》 · 《论新阶段》的核心论述"},
        "stem": "毛泽东正式提出\"马克思主义中国化\"命题是在（　）。",
        "options": [
            "1935年遵义会议",
            "1938年六届六中全会《论新阶段》报告",
            "1945年党的七大",
            "1949年七届二中全会",
        ],
        "answer": 1,
        "hint": "命题正式提出在《论新阶段》，不是遵义会议。",
        "explanation": "B正确。2.1.md：1938年六届六中全会毛泽东作《论新阶段》报告，正式提出马克思主义中国化命题。A遵义会议确立领导地位但未正式提出命题；C七大将毛泽东思想写入党章；D讨论新中国成立后政策。",
    },
    {
        "id": "q002", "type": "single_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 长征与遵义会议 · 三、遵义会议的召开 · 遵义会议"},
        "stem": "遵义会议召开的时间是（　）。",
        "options": ["1934年10月", "1935年1月", "1938年9月", "1945年4月"],
        "answer": 1,
        "hint": "长征途中、第五次反\"围剿\"失败后。",
        "explanation": "B正确。2.2.md定义：遵义会议1935年1月于贵州遵义召开。A是长征开始时间；C是六届六中全会；D是七大。",
    },
    {
        "id": "q003", "type": "single_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 长征与遵义会议 · 一、红军不怕远征难 · 长征的巨大牺牲"},
        "stem": "长征中，红一方面军从瑞金出发时约8.6万人，到达陕北时仅剩约（　）。",
        "options": ["3万人", "6000人", "1万人", "2万人"],
        "answer": 1,
        "hint": "区分全军30万→3万与红一方面军8.6万→？",
        "explanation": "B正确。2.2.md数据表：红一方面军从瑞金8.6万人，到达陕北仅剩约6000人。A是全军总数从30万到3万；C、D无依据。",
    },
    {
        "id": "q004", "type": "single_choice", "difficulty": "medium",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 长征与遵义会议 · 七、遵义会议的历史意义 · 独立自主的新起点"},
        "stem": "遵义会议的一个重要特点是（　）。",
        "options": [
            "在共产国际直接指示下召开",
            "在没有共产国际指示的情况下独立自主召开",
            "由王明在莫斯科遥控指挥",
            "主要讨论抗日战争战略方针",
        ],
        "answer": 1,
        "hint": "打破事事请示共产国际的惯例。",
        "explanation": "B正确。2.2.md：遵义会议在没有共产国际指示的情况下，中国共产党独立自主召开。A、C与\"独立自主\"相反；D当时主要讨论第五次反\"围剿\"失败和军事路线。",
    },
    {
        "id": "q005", "type": "single_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 三、命题提出后的迅速传播 · 从\"马克思主义中国化\"到\"中国化的马克思主义\""},
        "stem": "1945年党的七大上，毛泽东思想被确立为（　）。",
        "options": [
            "马克思主义中国化命题的首次提出",
            "党的一切工作的指针",
            "过渡时期总路线",
            "改革开放的指导思想",
        ],
        "answer": 1,
        "hint": "七大党章总纲的规定。",
        "explanation": "B正确。2.1.md：1945年七大党章总纲规定以毛泽东思想作为党一切工作的指针，是马克思主义中国化第一个重大理论成果。A是1938年六届六中全会；C是1953年；D是1978年后。",
    },
    {
        "id": "q006", "type": "single_choice", "difficulty": "medium",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 长征与遵义会议 · 四、遵义会议的过程 · 第四步：毛泽东的长篇发言"},
        "stem": "毛泽东在遵义会议上分析第五次反\"围剿\"军事错误，将其概括为（　）。",
        "options": [
            "左倾机会主义、右倾投降主义、宗派主义",
            "进攻时的冒险主义、防守时的保守主义、突围时的逃跑主义",
            "教条主义、经验主义、本位主义",
            "主观主义、宗派主义、党八股",
        ],
        "answer": 1,
        "hint": "单纯防御路线在不同阶段的三类表现。",
        "explanation": "B正确。2.2.md：毛泽东将军事上的单纯防御路线概括为进攻冒险主义、防守保守主义、突围逃跑主义。A、C、D是延安整风或其他语境中的错误类型表述。",
    },
    {
        "id": "q007", "type": "single_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 二、六届六中全会与《论新阶段》 · 六届六中全会的召开"},
        "stem": "1938年六届六中全会前，王稼祥从苏联带回的共产国际指示包括（　）。",
        "options": [
            "否定遵义会议以来党的政治路线",
            "肯定从遵义会议到陕北期间党的政治路线是正确的",
            "要求更换毛泽东的领导职务",
            "指示立即发动城市武装起义",
        ],
        "answer": 1,
        "hint": "共产国际指示两点重要内容之一。",
        "explanation": "B正确。2.1.md：共产国际指示两点——肯定遵义到陕北期间政治路线正确；强调以毛泽东为首。A与指示内容相反；C、D无依据。",
    },
    {
        "id": "q008", "type": "single_choice", "difficulty": "hard",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 五、\"两个结合\" · 中国现代化的起点：1861年"},
        "stem": "学者认为中国现代化探索的起点是1861年清政府设立总理衙门。同年环太平洋发生现代化变革的国家不包括（　）。",
        "options": ["中国", "俄国", "美国", "英国"],
        "answer": 3,
        "hint": "1861年四国：中俄美日。",
        "explanation": "D正确（选不包括）。2.1.md：1861年中俄美日四国都进行了现代化变革——中国设总理衙门、俄国农奴制改革、美国内战、日本明治维新（1868）。英国不在该年四国对比表中。",
    },
    {
        "id": "q009", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.1.md", "label": "1.1 课程介绍与教学安排 · 一、这是一门什么课程？ · 2. \"一二三四\"：课程的总体框架"},
        "stem": "（复习题）将毛泽东思想和中国特色社会主义理论体系连接在一起的纽带是（　）。",
        "options": [
            "新民主主义革命理论",
            "马克思主义中国化时代化",
            "四个现代化",
            "和平与发展",
        ],
        "answer": 1,
        "hint": "ch01\"一二三四\"框架中的\"一条主线\"。",
        "explanation": "B正确。1.1.md：纽带是马克思主义中国化时代化。A是毛泽东思想具体内容；C是现代化目标；D是邓小平时代主题。",
    },
    {
        "id": "q010", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.2.md", "label": "1.2 马克思主义中国化命题 · 二、马克思主义中国化时代化的提出 · 1. 马克思主义的传播路径"},
        "stem": "（复习题）\"十月革命一声炮响，给我们送来了马克思列宁主义\"说明马克思主义传入中国的路径是（　）。",
        "options": ["德国→中国", "德国→俄国→中国", "法国→中国", "英国→中国"],
        "answer": 1,
        "hint": "ch01已学传播路径。",
        "explanation": "B正确。1.2.md：德国创立→俄国发展→传入中国。A、C、D均忽略俄国环节。",
    },
    {
        "id": "q011", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.2.md", "label": "1.2 马克思主义中国化命题 · 三、中国式现代化 · 3. 中国式现代化的五大中国特色"},
        "stem": "（复习题）下列不属于中国式现代化五大特色的是（　）。",
        "options": [
            "人口规模巨大的现代化",
            "全体人民共同富裕的现代化",
            "先污染后治理的现代化",
            "走和平发展道路的现代化",
        ],
        "answer": 2,
        "hint": "五大特色之一是\"人与自然和谐共生\"。",
        "explanation": "C正确（选不属于）。1.2.md五大特色为人口规模巨大、共同富裕、两个文明协调、人与自然和谐共生、和平发展道路。C\"先污染后治理\"与生态文明建设方向相反。",
    },
    {
        "id": "q012", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.1.md", "label": "1.1 课程介绍与教学安排 · 一、这是一门什么课程？ · 1. 课程全称与核心定位"},
        "stem": "（复习题）本课程全称是（　）。",
        "options": [
            "马克思主义基本原理概论",
            "毛泽东思想和中国特色社会主义理论体系概论",
            "中国近现代史纲要",
            "思想道德与法治",
        ],
        "answer": 1,
        "hint": "简称\"毛概\"。",
        "explanation": "B正确。1.1.md：全称\"毛泽东思想和中国特色社会主义理论体系概论\"。A、C、D是其他四门思政课。",
    },
    {
        "id": "q013", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.2.md", "label": "1.2 马克思主义中国化命题 · 一、什么是马克思主义？ · 2. 人类解放的四个阶段"},
        "stem": "（复习题）马克思主义学说主要解决人类解放四阶段中的（　）。",
        "options": [
            "从自然界束缚中解放",
            "从封建等级制度束缚中解放",
            "从资本束缚中解放",
            "从自身束缚中解放",
        ],
        "answer": 2,
        "hint": "建立社会主义取代资本主义。",
        "explanation": "C正确。1.2.md：马克思主义主要解决第三阶段——从资本束缚中解放。A、B、D分别对应其他阶段。",
    },
    {
        "id": "q014", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.1.md", "label": "1.1 课程介绍与教学安排 · 三、教学安排与考核方式 · 2. 成绩构成"},
        "stem": "（复习题）本课程期末考试成绩占总成绩的（　）。",
        "options": ["30分", "40分", "50分", "60分"],
        "answer": 2,
        "hint": "平时与期末各占一半。",
        "explanation": "C正确。1.1.md：平时50分+期末50分。A、B、D与成绩构成表不符。",
    },
    {
        "id": "q015", "type": "single_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.2.md", "label": "1.2 马克思主义中国化命题 · 四、当代国际局势 · 2. 中美关系的历史演变"},
        "stem": "（复习题）2018年3月中美关系的重要变化是（　）。",
        "options": [
            "中美正式建交",
            "中美贸易冲突爆发，从贸易摩擦升级为技术遏制",
            "朝鲜战争爆发",
            "习近平首次访美",
        ],
        "answer": 1,
        "hint": "ch01中美关系演变时间表。",
        "explanation": "B正确。1.2.md：2018年3月中美贸易冲突爆发，升级为技术遏制。A是1979年；C是1950-1953年；D应为2015年习近平访美演讲获长时期掌声。",
    },
    {
        "id": "q016", "type": "multiple_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 四、马克思主义中国化时代化的内涵分析 · 三个构成要素"},
        "stem": "马克思主义中国化时代化内涵的三个构成要素包括（　）。",
        "options": [
            "马克思主义基本原理同中国具体实际相结合",
            "马克思主义基本原理同中国优秀传统文化相结合",
            "形成新的理论成果",
            "完全照搬苏联经验",
            "脱离时代特征",
        ],
        "answer": [0, 1, 2],
        "hint": "两个结合+理论成果。",
        "explanation": "ABC正确。2.1.md三个构成要素：与中国具体实际相结合、与优秀传统文化相结合、形成新理论成果。D是第五次反\"围剿\"失败的教训；E与\"时代化\"相悖。",
    },
    {
        "id": "q017", "type": "multiple_choice", "difficulty": "medium",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 长征与遵义会议 · 六、遵义会议的结果"},
        "stem": "遵义会议的重要决定包括（　）。",
        "options": [
            "改组中央领导机构",
            "增选毛泽东为中央政治局常委",
            "成立毛泽东、周恩来、王稼祥三人军事小组",
            "立即发动百团大战",
            "将毛泽东思想写入党章",
        ],
        "answer": [0, 1, 2],
        "hint": "三人军事小组在行军途中成立。",
        "explanation": "ABC正确。2.2.md：改组领导机构、增选毛泽东为常委、成立三人军事小组。D百团大战是1940年；E写入党章是1945年七大。",
    },
    {
        "id": "q018", "type": "multiple_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 六、从\"中国化\"到\"中国化时代化\" · 时代主题的变化与理论成果"},
        "stem": "时代主题与理论成果的对应关系中，正确的有（　）。",
        "options": [
            "毛泽东时代——战争与革命——毛泽东思想",
            "邓小平改革开放时期——和平与发展——邓小平理论",
            "上世纪90年代后——经济全球化加速——\"三个代表\"重要思想",
            "21世纪第二个十年至今——百年未有之大变局——习近平新时代中国特色社会主义思想",
            "毛泽东时代——和平与发展——毛泽东思想",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "每个理论成果回应特定时代课题。",
        "explanation": "ABCD正确。2.1.md时代主题与理论成果对应表。E错误——毛泽东思想对应战争与革命时代，非和平与发展。",
    },
    {
        "id": "q019", "type": "multiple_choice", "difficulty": "medium",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 长征与遵义会议 · 八、遵义会议前后的对比"},
        "stem": "遵义会议前后对比，下列表述正确的有（　）。",
        "options": [
            "会议前：博古等临时中央主导；会议后：毛泽东进入中央领导核心",
            "会议前：教条主义照搬\"本本\"；会议后：实事求是，马克思主义与中国实际相结合",
            "会议前：依赖共产国际指示；会议后：开始独立自主解决自身问题",
            "会议前：第五次反\"围剿\"胜利；会议后：继续遭受重大损失",
            "会议前：压制不同意见；会议后：鼓励独立思考、批评与自我批评",
        ],
        "answer": [0, 1, 2, 4],
        "hint": "会议前是失败和教条主义，会议后是转折。",
        "explanation": "ABCE正确。2.2.md对比表。D错误——会议前是第五次反\"围剿\"失败、损失惨重，会议后红军逐步走出困境。",
    },
    {
        "id": "q020", "type": "multiple_choice", "difficulty": "hard",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 五、\"两个结合\" · 从\"四个现代化\"到\"中国式现代化\""},
        "stem": "\"四个现代化\"到\"中国式现代化\"演进过程中，下列事件配对正确的有（　）。",
        "options": [
            "1954年第一届全国人大——首次提出四个现代化",
            "1978年全国科学大会——继续推进四个现代化",
            "2017年党的十九大——建设社会主义现代化强国",
            "2022年党的二十大——以中国式现代化全面推进中华民族伟大复兴",
            "1956年党的八大——首次提出中国式现代化",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "\"中国式现代化\"系统阐述在2022年二十大。",
        "explanation": "ABCD正确。2.1.md四个现代化到中国式现代化时间表。E错误——1956年八大是将四个现代化写入党章，非\"中国式现代化\"。",
    },
    {
        "id": "q021", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.1.md", "label": "1.1 课程介绍与教学安排 · 二、为什么要学习这门课程？ · 1. \"四个正确认识\""},
        "stem": "（复习题）\"四个正确认识\"包括（　）。",
        "options": [
            "正确认识世界和中国发展大势",
            "正确认识中国特色和国际比较",
            "正确认识时代责任和历史使命",
            "正确认识远大抱负和脚踏实地",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "ch01思政课总目标。",
        "explanation": "ABCD全部正确。1.1.md完整列出四个正确认识，无其他选项。",
    },
    {
        "id": "q022", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.2.md", "label": "1.2 马克思主义中国化命题 · 二、为什么必须\"中国化\"？"},
        "stem": "（复习题）关于\"马克思主义中国化\"的本质，下列表述正确的有（　）。",
        "options": [
            "不是要修改马克思主义基本原理",
            "是运用马克思主义立场、观点、方法研究和解决中国实际问题",
            "要求同中国具体实际相结合、同中华优秀传统文化相结合",
            "就是把苏联经验原封不动搬到中国",
            "是一劳永逸、不再发展的过程",
        ],
        "answer": [0, 1, 2],
        "hint": "中国化是运用而非修改，是过程而非一劳永逸。",
        "explanation": "ABC正确。1.2.md\"中国化的本质\"：运用而非修改，两个结合。D是\"照搬本本\"的错误；E与\"中国化时代化是持续推进的历史进程\"矛盾。",
    },
    {
        "id": "q023", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.1.md", "label": "1.1 课程介绍与教学安排 · 一、这是一门什么课程？ · 3. 两大理论成果的历史定位"},
        "stem": "（复习题）关于马克思主义中国化理论成果的历史定位，正确的有（　）。",
        "options": [
            "毛泽东思想——第一次历史性飞跃",
            "中国特色社会主义理论体系——最新成果（十七大）",
            "习近平新时代中国特色社会主义思想——新的飞跃（二十大）",
            "邓小平理论——第一次历史性飞跃",
        ],
        "answer": [0, 1, 2],
        "hint": "区分三次飞跃/定位表述。",
        "explanation": "ABC正确。1.1.md两大理论成果历史定位表。D错误——第一次历史性飞跃是毛泽东思想，邓小平理论是中特理论体系开篇之作。",
    },
    {
        "id": "q024", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.2.md", "label": "1.2 马克思主义中国化命题 · 四、当代国际局势 · 3. 拜登政府的五点核心判断"},
        "stem": "（复习题）2022年拜登政府国家安全战略对中国的判断包括（　）。",
        "options": [
            "应对中国挑战是美国的全球优先事务",
            "中国是唯一既有意愿也越来越有能力重塑国际秩序的竞争者",
            "未来十年是美中较量的决定性十年",
            "美国对华战略总目标是\"竞而胜之\"",
            "美国应与中国全面军事结盟",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "五点判断，非结盟。",
        "explanation": "ABCD正确。1.2.md拜登政府五点核心判断。E与竞争定位相反。",
    },
    {
        "id": "q025", "type": "multiple_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.2.md", "label": "1.2 马克思主义中国化命题 · 一、什么是马克思主义？ · 3. 资本主义制度的建立与批判"},
        "stem": "（复习题）关于资本主义制度，教材论述正确的有（　）。",
        "options": [
            "两大支柱是市场经济和民主政治",
            "恩格斯评价资本主义100年创造财富超过过去1000年",
            "1992年十四大后中国GDP飙升，2010成为世界第二",
            "马克思主义认为贫富分化根源是资本家对无产者的剥削",
            "资本主义制度没有任何积极历史作用",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "教材既分析积极性也批判问题。",
        "explanation": "ABCD正确。1.2.md资本主义分析：两大支柱、恩格斯评价、中国市场经济实践、马克思主义剥削论。E错误——教材明确承认资本主义\"积极性显而易见\"，创造了巨大财富。",
    },
    {
        "id": "q026", "type": "essay", "difficulty": "basic", "label": "简答题",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 10, "total_points": 10,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 长征与遵义会议 · 三、遵义会议的召开"},
        "stem": "简述遵义会议（1935年1月）的主要内容及其历史意义。",
        "answer": "主要内容：①背景——第五次反\"围剿\"失败，红军被迫长征；②过程——博古将失败归因客观因素，周恩来指出军事指挥错误并主动担责，张闻天尖锐批评，毛泽东长篇发言分析单纯防御路线（冒险主义、保守主义、逃跑主义）；③结果——改组中央领导机构，增选毛泽东为中央政治局常委，成立毛泽东、周恩来、王稼祥三人军事小组。\n\n历史意义：①确立毛泽东在党的领导地位，马克思主义与中国实际相结合的正确路线在党内占主导；②中国共产党第一次独立自主运用马克思列宁主义基本原理解决自己的路线、方针和政策，在没有共产国际指示下召开，标志政治上走向成熟。",
        "hint": "内容分背景、过程、结果；意义分领导地位和独立自主两点。",
        "explanation": "ch02-examples例题4提供了标准框架，依据2.2.md全文。",
        "scoring_criteria": [
            "正确概述会议背景与过程（4分）",
            "正确列出会议主要决定（3分）",
            "阐明两大历史意义（3分）",
        ],
    },
    {
        "id": "q027", "type": "essay", "difficulty": "medium", "label": "简答题",
        "source": "review", "sourceChapter": "ch01", "points": 10, "total_points": 10,
        "sourceRef": {"path": "content/maogai/detail/1.1.md", "label": "1.1 课程介绍与教学安排 · 一、这是一门什么课程？ · 2. \"一二三四\"：课程的总体框架"},
        "stem": "（复习题）简述本课程\"一二三四\"总体框架的具体内容。",
        "answer": "①\"一\"——一条主线：马克思主义中国化时代化；②\"二\"——两大理论：毛泽东思想与中国特色社会主义理论体系；③\"三\"——三个阶段：社会主义在中国的建立、建设、改革；④\"四\"——四个自信：道路自信、理论自信、制度自信、文化自信。将两大理论连接在一起的纽带正是马克思主义中国化时代化。毛泽东思想是中特理论体系的源头和基础，中特理论体系是对毛泽东思想的继承和发展。",
        "hint": "四个数字各对应一项内容。",
        "explanation": "1.1.md\"一二三四\"表格及两大理论关系note。",
        "scoring_criteria": [
            "正确表述\"一\"至\"四\"各项内容（6分）",
            "说明纽带与两大理论关系（3分）",
            "条理清楚（1分）",
        ],
    },
    {
        "id": "q028", "type": "essay", "difficulty": "hard", "label": "论述题",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 15, "total_points": 15,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 七、理论成果及其关系"},
        "stem": "论述毛泽东思想和中国特色社会主义理论体系的关系，并说明各理论成果与时代主题的对应关系。",
        "answer": "一、两者关系：一脉相承又与时俱进。一脉相承——都是马克思列宁主义在中国的运用和发展，都有独创性理论成果，都丰富发展马克思列宁主义。与时俱进——各成果在特定时代背景下形成，回应不同时代课题。教材以对外合作为例：50年代与苏联结盟→60年代亚非拉统一战线→70年代与西方和解→80年代不结盟→90年代伙伴关系→21世纪和谐世界→习近平构建人类命运共同体。\n\n二、时代主题与理论成果：毛泽东时代（战争与革命）→毛泽东思想，解决社会主义制度建立、中国人民\"站起来\"；邓小平时期（和平与发展）→邓小平理论，推动\"富起来\"；90年代后（经济全球化加速）→\"三个代表\"；21世纪第二个十年（百年变局）→习近平新时代中国特色社会主义思想，走向\"强起来\"。\n\n三、结论：党的二十大强调\"是中国化时代化的马克思主义行\"，体现认识不断深化。",
        "hint": "ch02-examples例题5提供了完整论述结构。",
        "explanation": "2.1.md第七部分及ch02-examples例题5。",
        "scoring_criteria": [
            "正确论述一脉相承又与时俱进（5分）",
            "准确对应时代主题与理论成果（5分）",
            "引用\"两个行\"等核心论断（3分）",
            "史论结合、条理清楚（2分）",
        ],
    },
    {
        "id": "q029", "type": "essay", "difficulty": "medium", "label": "材料分析题",
        "source": "current_chapter", "sourceChapter": "ch02", "points": 15, "total_points": 15,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 二、六届六中全会与《论新阶段》"},
        "stem": "阅读材料，回答问题。\n\n> 材料：\"没有抽象的马克思主义，只有具体的马克思主义。所谓具体的马克思主义，就是通过民族形式的马克思主义，就是把马克思主义应用到中国具体环境的具体斗争中去，而不是抽象地应用它。中国化是指在其每一表现中带有中国特性，即是说按照中国的特点去应用它，成为全党亟待了解并急需解决的问题。\"——毛泽东《论新阶段》（1938）\n\n（1）这一论述是在什么会议上首次提出的？（3分）\n（2）材料体现了马克思主义中国化的哪些核心要义？（6分）\n（3）从遵义会议到六届六中全会，中国共产党在思想路线上经历了怎样的深化？（6分）",
        "answer": "（1）1938年9月29日至10月6日党的六届六中全会上，毛泽东作《论新阶段》报告时正式提出\"马克思主义中国化\"命题。此前1938年7-8月王稼祥带回共产国际指示，肯定遵义以来路线正确、以毛泽东为首。\n\n（2）核心要义：①马克思主义不是抽象教条，必须与具体环境相结合；②\"中国化\"核心是\"按照中国的特点去应用\"，强调实践性和针对性；③使马克思主义在每一表现中带有中国特性；④这是全党\"亟待了解并急需解决的问题\"。\n\n（3）深化过程：遵义会议（1935）——确立毛泽东领导地位，开始独立自主运用马列主义解决路线方针政策问题，否定教条主义；六届六中全会（1938）——在共产国际认可基础上正式提出\"马克思主义中国化\"理论命题，从实践到理论、从政治到思想的升华。",
        "hint": "会议→要义→从遵义到六届六中全会的实践与理论深化。",
        "explanation": "材料直接引自2.1.md《论新阶段》论述，第三问联系2.2.md\"从遵义会议到六届六中全会\"。",
        "scoring_criteria": [
            "正确指出六届六中全会及背景（3分）",
            "准确概括核心要义（6分）",
            "阐明从遵义到六届六中全会的深化（6分）",
        ],
    },
]

CH03 = [
    {
        "id": "q001", "type": "single_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.1.md", "label": "3.1 毛泽东思想的形成和发展 · 一、历史条件 · （一）个人条件 · 4. 坚定的马克思主义者"},
        "stem": "毛泽东自何时起认为自己已经是马克思主义者，并且以后从未动摇过？",
        "options": ["1917年十月革命后", "1919年冬天", "1920年夏天", "1921年7月"],
        "answer": 2,
        "hint": "读三本马克思主义著作之后。",
        "explanation": "C正确。3.1.md：1919年冬读《共产党宣言》《阶级斗争》《社会主义史》后树立信仰，自1920年夏起认为已是马克思主义者且从未动摇。A是接触起点；B是读书时间；D是参加中共一大。",
    },
    {
        "id": "q002", "type": "single_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.2.md", "label": "3.2 毛泽东思想的主要内容 · 三、毛泽东思想的活的灵魂 · （一）实事求是"},
        "stem": "毛泽东对\"实事求是\"的马克思主义解释中，\"是\"是指（　）。",
        "options": [
            "客观存在着的一切事物",
            "客观事物的内部联系，即规律性",
            "我们去研究",
            "中国革命的具体实践",
        ],
        "answer": 1,
        "hint": "实事、是、求三字各指什么？",
        "explanation": "B正确。3.2.md定义：\"是\"就是客观事物的内部联系，即规律性。A是\"实事\"；C是\"求\"；D是结合对象而非\"是\"的含义。",
    },
    {
        "id": "q003", "type": "single_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.2.md", "label": "3.2 毛泽东思想的主要内容 · 引言 · 毛泽东思想的主要内容"},
        "stem": "贯穿毛泽东思想各个理论组成部分的活的灵魂是（　）。",
        "options": [
            "统一战线、武装斗争、党的建设",
            "实事求是、群众路线、独立自主",
            "理论联系实际、密切联系群众、批评与自我批评",
            "新民主主义革命、社会主义改造、社会主义建设",
        ],
        "answer": 1,
        "hint": "活的灵魂与三大法宝不同。",
        "explanation": "B正确。3.2.md：活的灵魂是实事求是、群众路线、独立自主。A是三大法宝；C是三大优良作风；D是理论组成部分。",
    },
    {
        "id": "q004", "type": "single_choice", "difficulty": "medium",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.1.md", "label": "3.1 毛泽东思想的形成和发展 · 二、形成和发展的过程 · （二）井冈山时期"},
        "stem": "毛泽东在《星星之火，可以燎原》中提出的革命道路理论是（　）。",
        "options": [
            "城市中心论",
            "农村包围城市、武装夺取政权",
            "和平过渡论",
            "议会道路论",
        ],
        "answer": 1,
        "hint": "井冈山时期的开创性道路。",
        "explanation": "B正确。3.1.md：井冈山时期提出建立农村根据地，以农村包围城市，最后武装夺取政权。A是照搬苏联模式；C、D不符合中国国情。",
    },
    {
        "id": "q005", "type": "single_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.3.md", "label": "3.3 毛泽东思想的历史地位 · 一、对毛泽东思想的科学评价 · （一）三句话的科学定性"},
        "stem": "对毛泽东思想的科学评价\"三句话\"中，说明其形成方式的是（　）。",
        "options": [
            "马克思列宁主义在中国的运用和发展",
            "被实践证明了的关于中国革命和建设的正确的理论原则和经验总结",
            "中国共产党集体智慧的结晶",
            "马克思主义中国化的第一次历史性飞跃",
        ],
        "answer": 2,
        "hint": "三句话分别说明理论来源、实践基础、形成方式。",
        "explanation": "C正确。3.3.md：第三句话\"中国共产党集体智慧的结晶\"说明形成方式和集体性质。A说明理论来源；B说明实践基础；D是历史定位表述，非三句话之一。",
    },
    {
        "id": "q006", "type": "single_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.3.md", "label": "3.3 毛泽东思想的历史地位 · 二、与中国特色社会主义理论体系的关系 · （三）党的十七大的理论贡献"},
        "stem": "将邓小平理论、\"三个代表\"重要思想和科学发展观统一纳入中国特色社会主义理论体系的概念，是在（　）提出的。",
        "options": ["党的七大", "党的十一届三中全会", "党的十七大", "党的十九大"],
        "answer": 2,
        "hint": "2007年的重要理论概括。",
        "explanation": "C正确。3.3.md：2007年党的十七大提出\"中国特色社会主义理论体系\"科学概念。A确立毛泽东思想；B开启改革开放；D提出习近平新时代中国特色社会主义思想。",
    },
    {
        "id": "q007", "type": "single_choice", "difficulty": "medium",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.1.md", "label": "3.1 毛泽东思想的形成和发展 · 二、形成和发展的过程 · （一）从调查研究到理论创造"},
        "stem": "1925年毛泽东在《中国社会各阶级的分析》等著作中得出的至关重要结论是（　）。",
        "options": [
            "革命的主体是城市工人阶级",
            "革命的成败取决于农民",
            "应当优先发展重工业",
            "中国应走议会民主道路",
        ],
        "answer": 1,
        "hint": "卡尔·马克思降临到亚洲的稻田上。",
        "explanation": "B正确。3.1.md：1925年调查研究后得出\"革命的成败取决于农民\"。A是经典马克思主义框架但不符合中国实际；C、D与毛泽东思想无关。",
    },
    {
        "id": "q008", "type": "single_choice", "difficulty": "hard",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.2.md", "label": "3.2 毛泽东思想的主要内容 · 四、理论成果及其科学评价"},
        "stem": "邓小平理论围绕的根本问题是（　）。",
        "options": [
            "什么是社会主义、怎样建设社会主义",
            "建设什么样的党、怎样建设党",
            "实现什么样的发展、怎样发展",
            "新时代坚持和发展什么样的中国特色社会主义",
        ],
        "answer": 0,
        "hint": "ch03-examples例题3考点。",
        "explanation": "A正确。3.2.md/ch03-examples：邓小平理论围绕\"什么是社会主义、怎样建设社会主义\"。B是\"三个代表\"；C是科学发展观；D是习近平新时代中国特色社会主义思想。",
    },
    {
        "id": "q009", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 二、六届六中全会与《论新阶段》"},
        "stem": "（复习题）\"马克思主义中国化\"命题正式提出的时间是（　）。",
        "options": ["1935年", "1938年", "1945年", "1949年"],
        "answer": 1,
        "hint": "六届六中全会《论新阶段》。",
        "explanation": "B正确。2.1.md：1938年六届六中全会正式提出。A是遵义会议；C是七大；D是新中国成立。",
    },
    {
        "id": "q010", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 长征与遵义会议 · 七、遵义会议的历史意义"},
        "stem": "（复习题）遵义会议的历史意义在于（　）。",
        "options": [
            "正式提出马克思主义中国化命题",
            "第一次独立自主运用马克思列宁主义基本原理解决自身路线方针政策问题",
            "将毛泽东思想写入党章",
            "确立过渡时期总路线",
        ],
        "answer": 1,
        "hint": "生死攸关的转折点。",
        "explanation": "B正确。2.2.md：遵义会议是第一次独立自主运用马列主义解决路线方针政策的会议。A是1938年六届六中全会；C是1945年七大；D是1953年。",
    },
    {
        "id": "q011", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 长征与遵义会议 · 一、长征的巨大牺牲"},
        "stem": "（复习题）第五次反\"围剿\"失败的根本原因是（　）。",
        "options": [
            "敌我力量对比过于悬殊，不可避免",
            "照搬本本，且照搬的是苏联的本本",
            "毛泽东未参与军事指挥",
            "共产国际明确指示错误",
        ],
        "answer": 1,
        "hint": "血的代价换来的四个字答案。",
        "explanation": "B正确。2.2.md：失败答案是\"照搬本本\"，且是苏联本本，未做到马克思主义与中国实际相结合。A是博古的借口；C、D与教材分析不符。",
    },
    {
        "id": "q012", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.1.md", "label": "1.1 课程介绍与教学安排 · 一、这是一门什么课程？ · 马克思主义中国化时代化"},
        "stem": "（复习题）马克思主义中国化时代化要求坚持把马克思主义基本原理同（　）相结合。",
        "options": [
            "中国具体实际和中华优秀传统文化",
            "苏联经验和西方文化",
            "封建传统文化和宗教思想",
            "市场经济和国际资本",
        ],
        "answer": 0,
        "hint": "ch01\"两个结合\"。",
        "explanation": "A正确。1.1.md定义：同中国具体实际相结合、同中华优秀传统文化相结合。B是\"照搬苏联本本\"的错误；C、D无依据。",
    },
    {
        "id": "q013", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 马克思主义中国化命题的提出 · 七、理论成果及其关系 · 两个\"行\""},
        "stem": "（复习题）党的二十大报告强调，归根到底是（　）。",
        "options": [
            "马克思主义行",
            "是中国化时代化的马克思主义行",
            "西方自由主义行",
            "苏联模式行",
        ],
        "answer": 1,
        "hint": "从\"一个行\"到\"两个行\"。",
        "explanation": "B正确。2.1.md：2022年二十大强调\"是中国化时代化的马克思主义行\"（在\"马克思主义行\"基础上深化）。A是2021年建党100周年表述；C、D与教材论断相反。",
    },
    {
        "id": "q014", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.2.md", "label": "1.2 马克思主义中国化命题 · 三、中国式现代化 · 1. 概念的提出"},
        "stem": "（复习题）系统阐述中国式现代化五大特色的会议是（　）。",
        "options": ["党的七大", "党的十一届三中全会", "党的十九大", "党的二十大"],
        "answer": 3,
        "hint": "2022年二十大报告。",
        "explanation": "D正确。1.2.md：2022年10月党的二十大系统阐述中国式现代化五大特色。A、B、C均非系统阐述五大特色的会议。",
    },
    {
        "id": "q015", "type": "single_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 · 三、命题提出后的迅速传播"},
        "stem": "（复习题）1942年朱德在纪念党的21周年文章中指出，\"中国化的马列主义\"的第一个成果是（　）。",
        "options": ["邓小平理论", "毛泽东思想", "科学发展观", "习近平新时代中国特色社会主义思想"],
        "answer": 1,
        "hint": "第一个重大理论成果。",
        "explanation": "B正确。2.1.md：1942年朱德正式使用\"中国化的马列主义\"，指出第一个成果是毛泽东思想。A、C、D是后续理论成果。",
    },
    {
        "id": "q016", "type": "multiple_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.2.md", "label": "3.2 毛泽东思想的主要内容 · 二、理论组成部分"},
        "stem": "毛泽东思想的主要理论组成部分包括（　）。",
        "options": [
            "新民主主义革命理论",
            "社会主义革命和社会主义建设理论",
            "革命军队建设和军事战略理论",
            "政策和策略理论",
            "思想政治工作和文化工作理论",
        ],
        "answer": [0, 1, 2, 3, 4],
        "hint": "还包括党的建设理论。",
        "explanation": "ABCDE全部正确。3.2.md引言及第二节列出六大组成部分（本题五项均在其中，第六项党的建设理论未列入选项但已选五项均正确）。",
    },
    {
        "id": "q017", "type": "multiple_choice", "difficulty": "medium",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.2.md", "label": "3.2 · 一、马克思主义中国化时代化的内涵 · 三层含义"},
        "stem": "马克思主义中国化时代化内涵的三层含义包括（　）。",
        "options": [
            "运用马克思主义立场观点方法分析和解决中国实际问题",
            "将中国革命建设改革实践经验提升为中国化的马克思主义理论",
            "将马克思主义植根于中华民族优秀文化沃土",
            "完全抛弃中国传统文化",
            "把马克思主义当作僵化教条",
        ],
        "answer": [0, 1, 2],
        "hint": "ch03-examples例题2。",
        "explanation": "ABC正确。3.2.md三层含义及ch03-examples例题2。D与\"两个结合\"相悖；E与\"不能把马克思主义当作僵化教条\"相反。",
    },
    {
        "id": "q018", "type": "multiple_choice", "difficulty": "basic",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.3.md", "label": "3.3 · 一、科学评价 · 两个不能否定"},
        "stem": "\"两个不能否定\"原则要求（　）。",
        "options": [
            "不能用改革开放后的历史时期否定改革开放前的历史时期",
            "不能用改革开放前的历史时期否定改革开放后的历史时期",
            "把毛泽东同志功绩和晚年错误区别开来",
            "把毛泽东思想科学体系和毛泽东同志晚年错误理论区别开来",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "科学评价毛泽东思想的基本原则。",
        "explanation": "ABCD全部正确。3.3.md\"两个不能否定\"定义及具体要求——区分功绩与错误、科学体系与晚年错误。",
    },
    {
        "id": "q019", "type": "multiple_choice", "difficulty": "medium",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.1.md", "label": "3.1 · 一、个人条件 · 四个突出特征"},
        "stem": "教材归纳的毛泽东四个突出个人特征包括（　）。",
        "options": [
            "不畏强权，敢于反抗封建专制制度的压迫",
            "对社会穷苦人民的深深同情",
            "坚定的民族独立关切",
            "坚定的马克思主义者",
            "优先出国留学接受西方教育",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "毛泽东选择留在中国而非赴法留学。",
        "explanation": "ABCD正确。3.1.md四个突出特征。E错误——1919年毛泽东送蔡和森赴法但自己未去，认为\"把时间花在中国会更有用处\"。",
    },
    {
        "id": "q020", "type": "multiple_choice", "difficulty": "hard",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.2.md", "label": "3.2 · 一、四个历史阶段"},
        "stem": "马克思主义中国化时代化四个历史阶段对民族复兴的贡献，配对正确的有（　）。",
        "options": [
            "新民主主义革命时期——实现中国从几千年封建专制政治向人民民主的伟大飞跃",
            "社会主义革命和建设时期——奠定根本政治前提和制度基础",
            "改革开放时期——提供充满新活力的体制保证和快速发展的物质条件",
            "新时代——实现中华民族伟大复兴进入不可逆转的历史进程",
            "新民主主义革命时期——实现从站起来到富起来的飞跃",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "\"站起来到富起来\"是改革开放时期的表述。",
        "explanation": "ABCD正确。3.2.md四个历史阶段表。E错误——从站起来到富起来是改革开放时期的成就，新民主主义革命实现的是向人民民主的伟大飞跃。",
    },
    {
        "id": "q021", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 · 四、三个构成要素"},
        "stem": "（复习题）马克思主义中国化时代化三个构成要素包括（　）。",
        "options": [
            "与中国具体实际相结合",
            "与中国优秀传统文化相结合",
            "形成新的理论成果",
            "照搬苏联军事经验",
        ],
        "answer": [0, 1, 2],
        "hint": "ch02已学三个构成要素。",
        "explanation": "ABC正确。2.1.md三个构成要素。D是遵义会议批判的错误。",
    },
    {
        "id": "q022", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 · 四、遵义会议的过程"},
        "stem": "（复习题）遵义会议上的发言与态度，下列表述正确的有（　）。",
        "options": [
            "博古承认军事错误但将失败主因归于客观因素",
            "周恩来明确指出失败主要原因是军事指挥错误并主动担责",
            "张闻天尖锐批评第五次反\"围剿\"军事错误",
            "毛泽东分析单纯防御路线的三种错误表现",
            "凯丰完全同意毛泽东意见",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "凯丰反对毛泽东意见。",
        "explanation": "ABCD正确。2.2.md会议过程。E错误——凯丰明确表示不同意毛泽东、张闻天、王稼祥的意见。",
    },
    {
        "id": "q023", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.2.md", "label": "1.2 · 三、中国式现代化五大特色"},
        "stem": "（复习题）中国式现代化五大特色包括（　）。",
        "options": [
            "人口规模巨大的现代化",
            "全体人民共同富裕的现代化",
            "物质文明和精神文明相协调的现代化",
            "人与自然和谐共生的现代化",
            "走和平发展道路的现代化",
        ],
        "answer": [0, 1, 2, 3, 4],
        "hint": "ch01核心主线内容。",
        "explanation": "ABCDE全部正确。1.2.md五大特色完整列表。",
    },
    {
        "id": "q024", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch02", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 · 七、理论成果及其关系"},
        "stem": "（复习题）马克思主义中国化时代化重大理论成果与历史贡献配对正确的有（　）。",
        "options": [
            "毛泽东思想——使中国人\"站起来\"",
            "邓小平理论——推动中国\"富起来\"",
            "习近平新时代中国特色社会主义思想——从\"富起来\"走向\"强起来\"",
            "科学发展观——成功在新形势下坚持和发展中国特色社会主义",
            "毛泽东思想——开创中国特色社会主义",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "开创中国特色社会主义的是邓小平理论。",
        "explanation": "ABCD正确。2.1.md理论成果表。E错误——开创中国特色社会主义的是邓小平理论，毛泽东思想解决的是\"站起来\"。",
    },
    {
        "id": "q025", "type": "multiple_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch01", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/1.1.md", "label": "1.1 · 五门思政课的逻辑关系"},
        "stem": "（复习题）五门思政课定位配对正确的有（　）。",
        "options": [
            "思想道德与法治——修身课",
            "中国近现代史纲要——历史课",
            "马克思主义基本原理——理论课",
            "毛概——治国课",
            "习近平新时代中国特色社会主义思想——历史课",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "新时代课是习近平新时代中国特色社会主义思想概论。",
        "explanation": "ABCD正确。1.1.md五门课表格。E错误——习近平新时代中国特色社会主义思想概论是\"新时代课\"，非历史课。",
    },
    {
        "id": "q026", "type": "essay", "difficulty": "basic", "label": "简答题",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 10, "total_points": 10,
        "sourceRef": {"path": "content/maogai/detail/3.1.md", "label": "3.1 · 一、个人条件 · 四个突出特征"},
        "stem": "简述毛泽东身上四个突出的个人特征及其具体表现。",
        "answer": "①不畏强权——13岁与专制式父亲争吵、私塾拒绝不合理礼节并\"罢课\"出走、1924年在船上与流氓打斗；②对穷苦人民深深同情——分午饭给贫困同学、送两担白米给乞讨大婶、帮邻居抢收稻谷、1906年长沙抢米暴动中同情\"普通人\"；③坚定民族独立关切——1919年送蔡和森赴法但自己不去，认为\"把时间花在中国会更有用处\"；④坚定马克思主义者——1919年冬读《共产党宣言》等三书，1920年夏起自认马克思主义者且从未动摇，1921年参加中共一大。",
        "hint": "ch03-examples例题4提供了完整答题要点。",
        "explanation": "3.1.md四个特征及ch03-examples例题4。",
        "scoring_criteria": [
            "正确列出四个特征（4分）",
            "各举一点具体表现（5分）",
            "条理清楚（1分）",
        ],
    },
    {
        "id": "q027", "type": "essay", "difficulty": "medium", "label": "简答题",
        "source": "review", "sourceChapter": "ch02", "points": 10, "total_points": 10,
        "sourceRef": {"path": "content/maogai/detail/2.1.md", "label": "2.1 · 四、三个构成要素"},
        "stem": "（复习题）简述马克思主义中国化时代化内涵的三个构成要素。",
        "answer": "①马克思主义基本原理同中国具体实际相结合——运用马克思主义立场观点方法，解决中国革命、建设、改革中的实际问题，核心命题是中国式现代化道路；②马克思主义基本原理同中国优秀传统文化相结合——使理论具有中国特色、中国风格和中国气派（如\"实事求是\"\"愚公移山\"）；③形成新的理论成果——产生中国化的马克思主义理论，如毛泽东思想、中国特色社会主义理论体系等。",
        "hint": "两个结合+理论成果。",
        "explanation": "2.1.md第四部分三个构成要素表。",
        "scoring_criteria": [
            "正确表述第一个结合（3分）",
            "正确表述第二个结合（3分）",
            "正确表述形成新理论成果（3分）",
            "条理清楚（1分）",
        ],
    },
    {
        "id": "q028", "type": "essay", "difficulty": "hard", "label": "论述题",
        "source": "current_chapter", "sourceChapter": "ch03", "points": 15, "total_points": 15,
        "sourceRef": {"path": "content/maogai/detail/3.3.md", "label": "3.3 · 毛泽东思想的历史地位"},
        "stem": "论述毛泽东思想的历史地位，并说明毛泽东思想与中国特色社会主义理论体系的关系。",
        "answer": "一、历史地位（五个方面）：①理论地位——马克思主义中国化第一次历史性飞跃；②实践地位——被实践证明了的关于中国革命和建设的正确理论原则和经验总结；③组织地位——中国共产党集体智慧的结晶；④指导地位——党必须长期坚持的指导思想；⑤传承地位——为中特理论体系提供根本遵循和理论准备。\n\n二、与中特理论体系关系：①毛泽东思想活的灵魂（实事求是、群众路线、独立自主）被中特理论体系全面继承发展；②毛泽东关于社会主义建设的重要思想（如正确处理人民内部矛盾、统筹兼顾）为开创中特做了理论准备；③中特理论体系不是简单重复，而是在新历史条件下丰富发展毛泽东思想；④2007年十七大提出\"中特理论体系\"概念，明确二者关系框架。\n\n三、结论：二者体现马克思主义中国化继承与发展的辩证统一——继承基本立场观点方法，发展是根据新历史条件推进理论创新。",
        "hint": "从三句话评价、五个地位、与中特关系三方面展开。",
        "explanation": "3.3.md全文及总结部分。",
        "scoring_criteria": [
            "准确概括毛泽东思想历史地位（5分）",
            "正确论述与中特理论体系关系（5分）",
            "引用\"活的灵魂\"传承等关键论据（3分）",
            "史论结合、条理清楚（2分）",
        ],
    },
    {
        "id": "q029", "type": "essay", "difficulty": "medium", "label": "材料分析题",
        "source": "review", "sourceChapter": "ch02", "points": 15, "total_points": 15,
        "sourceRef": {"path": "content/maogai/detail/2.2.md", "label": "2.2 · 一、长征的巨大牺牲"},
        "stem": "阅读材料，回答问题。\n\n> 材料：\"从30万人到3万人，从8.6万人到6000人——无数红军将士用自己的生命为代价，向中国共产党人提出了一个必须回答的问题：为什么会失败？答案是四个字——照搬本本。而且照搬的不是马克思的本本，是苏联的本本。\"\n\n（1）材料中的数据说明了什么？（4分）\n（2）\"照搬本本\"在第五次反\"围剿\"中具体表现为什么？（6分）\n（3）这一历史教训与马克思主义中国化命题的提出有何内在联系？（5分）",
        "answer": "（1）说明长征代价极其惨重——全军约30万人仅3万人到达陕北，红一方面军8.6万人仅6000人到达，是用生命换来的惨痛教训，也是遵义会议召开和马克思主义中国化命题提出的血泪起点。\n\n（2）具体表现：临时中央博古等人照搬苏联军事经验和革命模式，实行军事上的单纯防御路线——进攻时冒险主义、防守时保守主义、突围时逃跑主义；不考虑中国革命战争以弱敌强、游击战为主的具体特点，陷入被动挨打。\n\n（3）内在联系：血的教训使党认识到必须将马克思主义与中国实际相结合而非照搬外国经验→遵义会议确立毛泽东领导地位和独立自主解决中国问题方向→1938年六届六中全会正式提出\"马克思主义中国化\"命题，从实践教训上升为理论自觉。",
        "hint": "数据→教条主义表现→与中国化命题的逻辑链。",
        "explanation": "材料引自2.2.md，第二问联系教条主义定义和\"三反\"错误，第三问联系2.1.md命题提出背景。",
        "scoring_criteria": [
            "正确解读数据含义（4分）",
            "准确分析\"照搬本本\"的具体表现（6分）",
            "阐明与马克思主义中国化命题的内在联系（5分）",
        ],
    },
]
