# Part 3: CH10-CH12 question data

CH10 = [
    {
        "id": "q001", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "《论十大关系》的基本构成"},
        "stem": "1956年4月毛泽东作《论十大关系》报告，其围绕的基本方针是（　）。",
        "options": [
            "把国内外一切积极因素调动起来，为社会主义事业服务",
            "以阶级斗争为纲，继续革命",
            "优先发展轻工业，放弃重工业",
            "全面照搬苏联建设模式",
        ],
        "answer": 0,
        "hint": "十大关系都围绕一个基本方针展开。",
        "explanation": "A正确。16.1.md：《论十大关系》围绕把国内外一切积极因素调动起来为社会主义事业服务这一基本方针。B、C、D均与报告精神不符。",
    },
    {
        "id": "q002", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "基本方针"},
        "stem": "《论十大关系》运用的方法论是（　）。",
        "options": ["唯物辩证法的矛盾分析法", "历史虚无主义方法", "纯经验归纳法", "先验演绎法"],
        "answer": 0,
        "hint": "从矛盾双方对立统一分析每一对关系。",
        "explanation": "A正确。16.2.md：核心方法论是唯物辩证法的矛盾分析法，分析每对关系中双方地位、作用及转化条件。",
    },
    {
        "id": "q003", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "社会主义社会的主要矛盾"},
        "stem": "1956年党的八大指出，社会主义制度建立后国内的主要矛盾是（　）。",
        "options": [
            "人民对于建立先进的工业国的要求同落后的农业国的现实之间的矛盾",
            "工人阶级与资产阶级的矛盾",
            "帝国主义与中华民族的矛盾",
            "地主阶级与农民阶级的矛盾",
        ],
        "answer": 0,
        "hint": "八大对主要矛盾的判断是初步探索的重要成果。",
        "explanation": "A正确。16.1.md：八大指出主要矛盾是人民对先进工业国要求同落后农业国现实、对经济文化迅速发展需要同当前不能满足状况之间的矛盾。B是过渡时期主要矛盾；C、D是近代中国或土改前矛盾。",
    },
    {
        "id": "q004", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "根本任务"},
        "stem": "社会主义社会的根本任务是（　）。",
        "options": ["发展生产力", "继续大规模阶级斗争", "恢复资本主义私有制", "关闭国门搞建设"],
        "answer": 0,
        "hint": "主要矛盾决定根本任务。",
        "explanation": "A正确。16.1.md：根本任务是发展生产力，把工作重点转到技术革命和社会主义建设上来。B、C、D均与教材论述相反。",
    },
    {
        "id": "q005", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "重工业与轻工业、农业的关系"},
        "stem": "毛泽东在《论十大关系》中论及重工业与轻工业、农业关系时指出（　）。",
        "options": [
            "重工业是重点必须优先发展，但也不能忽视农业和轻工业",
            "可以因此完全放弃重工业",
            "应像苏联那样片面强调重工业而忽视农业",
            "农业、轻工业与重工业毫无关系",
        ],
        "answer": 0,
        "hint": "多发展农业轻工业，反而能更好发展重工业。",
        "explanation": "A正确。16.2.md：重工业是重点必须优先发展，但绝不可因此忽视生活资料尤其是粮食生产；多发展农业轻工业反而能更好发展重工业。B、C、D与论述相反。",
    },
    {
        "id": "q006", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "两个积极性"},
        "stem": "处理中央和地方关系应坚持的原则是（　）。",
        "options": [
            "在中央统一领导下，充分发挥中央和地方两个积极性",
            "完全取消中央领导，地方各自为政",
            "只强调中央积极性，取消地方任何权力",
            "让地方完全替代中央职能",
        ],
        "answer": 0,
        "hint": "两个积极性比一个积极性好得多。",
        "explanation": "A正确。16.2.md：在巩固中央统一领导前提下扩大地方权力，两个积极性比只有一个好。B、C、D均片面。",
    },
    {
        "id": "q007", "type": "single_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "从\"以苏为鉴\"到\"走自己的路\""},
        "stem": "《论十大关系》的核心出发点是（　）。",
        "options": ["以苏为鉴，探索中国自己的社会主义建设道路", "全盘否定苏联所有经验", "完全停止学习外国", "回归资本主义道路"],
        "answer": 0,
        "hint": "苏联暴露缺点和错误，不能再走其弯路。",
        "explanation": "A正确。16.2.md：核心出发点是以苏为鉴，结合中国国情探索自己的道路。B“全盘否定”与“有分析有批判地学”不符；C、D错误。",
    },
    {
        "id": "q008", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "四个现代化"},
        "stem": "“四个现代化”是指（　）。",
        "options": [
            "工业、农业、国防和科学技术现代化",
            "工业、商业、金融、服务业现代化",
            "农业、手工业、资本主义工商业、国防现代化",
            "政治、经济、文化、军事全面西化",
        ],
        "answer": 0,
        "hint": "1964年周恩来在三届全国人大一次会议上正式提出。",
        "explanation": "A正确。16.1.md：四个现代化是工业、农业、国防和科学技术现代化。B、C、D均不符合定义。",
    },
    # review from earlier chapters
    {
        "id": "q009", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch09", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/9.3.md", "label": "改造促进生产力发展"},
        "stem": "1956年底社会主义改造基本完成，标志着（　）。",
        "options": [
            "社会主义基本制度在中国确立",
            "新民主主义革命刚刚开始",
            "改革开放正式启动",
            "资本主义制度在中国复辟",
        ],
        "answer": 0,
        "hint": "三大改造1956年底基本完成。",
        "explanation": "A正确。9.3.md：1956年底三大改造基本完成，社会主义基本制度确立。B、C、D时间或性质错误。",
    },
    {
        "id": "q010", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch12", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/12.3.md", "label": "独立自主催生了中国式道路"},
        "stem": "中苏关系变化客观上推动中国（　）。",
        "options": [
            "从苏联模式中剥离，独立自主探索中国式社会主义建设道路",
            "完全依赖苏联模式",
            "放弃社会主义制度",
            "与所有社会主义国家断交",
        ],
        "answer": 0,
        "hint": "《论十大关系》是探索中国道路的开篇。",
        "explanation": "A正确。12.3.md：中苏争吵和争斗过程中，中国从苏联模式剥离，《论十大关系》开始探索中国道路。B、C、D与史实相反。",
    },
    {
        "id": "q011", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch08", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/8.2.md", "label": "优先发展重工业的战略逻辑"},
        "stem": "一五计划156项工程中，轻工业和医药项目数量约为（　）。",
        "options": ["3个", "24个", "27个", "156个"],
        "answer": 0,
        "hint": "绝大多数集中在重工业领域。",
        "explanation": "A正确。8.2.md：156项中轻工业+医药仅3个，体现优先发展重工业。B是机械；C是煤炭；D是总数。",
    },
    {
        "id": "q012", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "处理人民内部矛盾的基本方法"},
        "stem": "处理人民内部矛盾的基本方法是（　）。",
        "options": ["团结—批评—团结", "专政镇压", "军事斗争", "经济制裁"],
        "answer": 0,
        "hint": "敌我矛盾用专政，人民内部矛盾用民主。",
        "explanation": "A正确。16.1.md：人民内部矛盾用民主方法，基本公式是团结—批评—团结。B是敌我矛盾方法。",
    },
    {
        "id": "q013", "type": "single_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "基本矛盾与主要矛盾的关系"},
        "stem": "社会主义社会基本矛盾与主要矛盾的关系，正确的是（　）。",
        "options": [
            "基本矛盾贯穿始终，主要矛盾是其在特定历史阶段的集中体现",
            "基本矛盾会随阶段变化而消失",
            "主要矛盾就是敌我矛盾",
            "基本矛盾是对抗性的，不可解决",
        ],
        "answer": 0,
        "hint": "基本矛盾：生产力与生产关系、经济基础与上层建筑。",
        "explanation": "A正确。16.2.md：基本矛盾是总根源贯穿始终；主要矛盾是特定阶段最突出问题。B基本矛盾只要社会主义存在就存在；C八大主要矛盾是人民内部性质；D基本矛盾是非对抗性的。",
    },
    {
        "id": "q014", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "一纲四目"},
        "stem": "“一纲四目”中“一纲”是指（　）。",
        "options": ["台湾必须统一于中国", "台湾实行完全独立", "国共两党轮流执政", "放弃对台主权要求"],
        "answer": 0,
        "hint": "和平解决台湾问题的政策主张。",
        "explanation": "A正确。16.1.md：“一纲”是台湾必须统一于中国。B、C、D均违背一纲。",
    },
    {
        "id": "q015", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "两个30年的关系"},
        "stem": "关于改革开放前后两个历史时期的关系，正确的是（　）。",
        "options": [
            "前者为后者积累条件，后者是对前者的坚持、改革和发展",
            "可以用后者完全否定前者",
            "可以用前者完全否定后者",
            "两者没有任何联系",
        ],
        "answer": 0,
        "hint": "两个30年一脉相承又与时俱进。",
        "explanation": "A正确。16.1.md：不能相互否定，前者为后者积累条件，后者是坚持、改革和发展。B、C、D均错误。",
    },
    # multiples - all review
    {
        "id": "q016", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "两类不同性质的矛盾及其处理办法"},
        "stem": "社会主义社会两类不同性质矛盾的正确配对有（　）。",
        "options": [
            "敌我矛盾——对抗性——专政方法",
            "人民内部矛盾——非对抗性——民主方法",
            "人民内部矛盾——对抗性——专政方法",
            "敌我矛盾——非对抗性——团结批评团结",
            "人民内部矛盾基本方法——团结—批评—团结",
        ],
        "answer": [0, 1, 4],
        "hint": "性质与处理方法必须对应。",
        "explanation": "ABE正确。16.1.md表格。C、D性质与方法配对错误。",
    },
    {
        "id": "q017", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "不同领域人民内部矛盾的方针"},
        "stem": "正确处理人民内部矛盾在不同领域的方针包括（　）。",
        "options": [
            "政治思想领域——团结—批评—团结",
            "科学文化领域——百花齐放、百家争鸣",
            "党与民主党派——长期共存、互相监督",
            "民族关系——民族平等、团结互助、共同繁荣",
            "敌我矛盾——惩前毖后、治病救人",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "惩前毖后、治病救人是处理是非关系（人民内部）。",
        "explanation": "ABCD正确。16.1.md各领域方针表。E中“惩前毖后、治病救人”用于是非关系（人民内部），不用于敌我矛盾。",
    },
    {
        "id": "q018", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "调动一切积极因素的两个坚持"},
        "stem": "调动一切积极因素为社会主义事业服务，必须坚持（　）。",
        "options": ["中国共产党的领导", "社会主义道路", "资本主义道路", "无政府状态", "多党轮流执政"],
        "answer": [0, 1],
        "hint": "两个坚持在教材96页。",
        "explanation": "AB正确。16.1.md两个坚持。C、D、E均不符合。",
    },
    {
        "id": "q019", "type": "multiple_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "十大关系一览总表"},
        "stem": "《论十大关系》中属于中国工业化道路层面的关系有（　）。",
        "options": [
            "重工业和轻工业、农业的关系",
            "沿海工业和内地工业的关系",
            "经济建设和国防建设的关系",
            "汉族和少数民族的关系",
            "中国和外国的关系",
        ],
        "answer": [0, 1, 2],
        "hint": "前三条聚焦工业化道路。",
        "explanation": "ABC正确。16.1.md/16.2.md：前三条属工业化道路；D、E属政治思想文化领域。",
    },
    {
        "id": "q020", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "初步探索的重要意义"},
        "stem": "社会主义建设道路初步探索的重要意义包括（　）。",
        "options": [
            "巩固和发展了社会主义制度",
            "为开创中国特色社会主义提供了经验、理论准备和物质基础",
            "丰富了科学社会主义理论和实践",
            "完全消除了此后一切探索曲折",
            "证明中国不应进行任何社会主义建设",
        ],
        "answer": [0, 1, 2],
        "hint": "教材110-112页三个方面。",
        "explanation": "ABC正确。16.1.md三方面意义。D、E与教材及史实不符。",
    },
    {
        "id": "q021", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "社会主义社会的基本矛盾"},
        "stem": "社会主义社会基本矛盾的特点包括（　）。",
        "options": [
            "仍是生产力与生产关系、经济基础与上层建筑的矛盾",
            "是非对抗性矛盾",
            "可通过社会主义制度自我调整和完善解决",
            "与旧社会基本矛盾性质完全相同",
            "一经建立就不再存在任何矛盾",
        ],
        "answer": [0, 1, 2],
        "hint": "基本矛盾贯穿社会主义社会始终。",
        "explanation": "ABC正确。16.1.md基本矛盾定义。D性质根本不同；E否认矛盾客观存在。",
    },
    {
        "id": "q022", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "积极因素与消极因素的辩证法"},
        "stem": "关于积极因素与消极因素，正确的有（　）。",
        "options": [
            "积极因素在社会主义条件下处于主导地位",
            "消极因素客观存在，不能忽视",
            "二者在一定条件下可以相互转化",
            "消极因素永远占主导地位",
            "只要忽视消极因素，它们会自动消失",
        ],
        "answer": [0, 1, 2],
        "hint": "三个关键命题。",
        "explanation": "ABC正确。16.2.md三个关键命题。D、E与辩证法相反。",
    },
    {
        "id": "q023", "type": "multiple_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "经验教训"},
        "stem": "初步探索的经验教训包括（　）。",
        "options": [
            "必须把马克思主义与中国实际相结合",
            "必须正确认识主要矛盾和根本任务，集中力量发展生产力",
            "建设规模和速度要与国力相适应",
            "必须发展社会主义民主，健全社会主义法制",
            "必须关起门来搞建设，拒绝一切外援",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "第六条教训是坚持对外开放。",
        "explanation": "ABCD正确。16.1.md六条教训前四条及民主法制、对外开放等。E与“必须坚持对外开放”相反。",
    },
    {
        "id": "q024", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch08", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/8.1.md", "label": "新民主主义社会的过渡性"},
        "stem": "新民主主义社会过渡性的原因包括（　）。",
        "options": [
            "78.7%私有经济与21.3%公有经济并存，非稳定态",
            "工人阶级与资产阶级矛盾推动所有制变革",
            "苏联模式示范效应",
            "政治制度与经济制度完全匹配、可长期维持",
            "前途明确走向社会主义",
        ],
        "answer": [0, 1, 2, 4],
        "hint": "8.1.md因果分析三个因素+历史定位。",
        "explanation": "ABCE正确。8.1.md三个决定因素及属于社会主义体系。D与“不匹配”论述相反。",
    },
    {
        "id": "q025", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "中国工业化道路"},
        "stem": "中国工业化道路的基本方针包括（　）。",
        "options": [
            "以农业为基础",
            "以工业为主导",
            "以农轻重为序发展国民经济",
            "完全忽视农业只搞重工业",
            "以重工业为中心同时充分注意农业和轻工业",
        ],
        "answer": [0, 1, 2, 4],
        "hint": "16.1.md走中国工业化道路定义。",
        "explanation": "ABCE正确。16.1.md：以农业为基础、工业为主导、农轻重为序，以重工业为中心同时注意农业轻工业。D与苏联片面强调重工业的教训相反。",
    },
    # essays
    {
        "id": "q026", "type": "essay", "difficulty": "basic", "label": "简答题",
        "source": "review", "sourceChapter": "ch16", "points": 10, "total_points": 10,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "两类不同性质的矛盾及其处理办法"},
        "stem": "简述社会主义社会两类不同性质矛盾的内容及处理方法。",
        "answer": "①敌我矛盾：人民同敌视、破坏社会主义建设的敌对势力之间的矛盾，属对抗性矛盾，处理方法是用专政的方法（依法打击、镇压）。②人民内部矛盾：人民内部各阶层、各群体之间的利益差异和思想分歧，属非对抗性矛盾，处理方法是用民主的方法，基本公式是“团结—批评—团结”。社会主义制度建立后，正确处理人民内部矛盾成为国家政治生活的主题。",
        "hint": "分类+性质+方法+主题转变。",
        "explanation": "16.1.md是ch10 stub核心内容。",
        "scoring_criteria": ["敌我矛盾界定与处理方法（4分）", "人民内部矛盾界定与处理方法（4分）", "政治生活主题转变（2分）"],
    },
    {
        "id": "q027", "type": "essay", "difficulty": "medium", "label": "简答题",
        "source": "review", "sourceChapter": "ch16", "points": 10, "total_points": 10,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "十大关系一览总表"},
        "stem": "列举《论十大关系》中的十对关系，并说明其三个层面的结构。",
        "answer": "十对关系：①重工业和轻工业、农业；②沿海工业和内地工业；③经济建设和国防建设；④国家、生产单位和生产者个人；⑤中央和地方；⑥汉族和少数民族；⑦共产党和民主党派；⑧革命和反革命；⑨是非；⑩中国和外国的关系。三个层面：前三条属中国工业化道路（怎样发展经济）；中间两条属经济体制改革（怎样调动积极性）；后五条属政治生活和思想文化领域（怎样调动全社会积极性）。",
        "hint": "先列十对，再分三层。",
        "explanation": "16.1.md基本构成与16.2.md内在结构。",
        "scoring_criteria": ["十对关系完整（5分）", "三个层面划分准确（5分）"],
    },
    {
        "id": "q028", "type": "essay", "difficulty": "medium", "label": "论述题",
        "source": "review", "sourceChapter": "ch16", "points": 15, "total_points": 15,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "从十大关系到矛盾学说的理论升华"},
        "stem": "论述《论十大关系》在探索中国社会主义建设道路中的理论意义。",
        "answer": "时代背景：1956年苏共二十大反思斯大林问题，国内改造完成、照搬苏联模式暴露弊端。《论十大关系》以矛盾分析法为工具，以调动一切积极因素为基本方针，系统梳理十对重大关系，是从“以苏为鉴”到“走自己的路”的开篇之作。理论贡献：①经济领域提出不同于苏联片面强调重工业的思路，强调农轻重关系、沿海与内地、经济与国防等辩证统一；②体制领域提出两个积极性、兼顾国家集体个人利益；③政治文化领域提出正确处理人民内部矛盾的一系列方针。方法论上构建矛盾分析框架——区分基本矛盾与主要矛盾、敌我矛盾与人民内部矛盾、积极因素与消极因素，为《关于正确处理人民内部矛盾的问题》奠定基础。意义：为后来改革开放和中国特色社会主义提供理论渊源，丰富科学社会主义。",
        "hint": "背景+方针+结构+方法论+意义。",
        "explanation": "16.2.md第五、六节及16.1.md意义部分。",
        "scoring_criteria": ["背景与基本方针（3分）", "十大关系结构与核心观点（5分）", "矛盾分析方法论（4分）", "历史意义（3分）"],
    },
    {
        "id": "q029", "type": "essay", "difficulty": "hard", "label": "材料分析题",
        "source": "review", "sourceChapter": "ch16", "points": 15, "total_points": 15,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "重工业与轻工业、农业的关系"},
        "stem": "阅读材料，回答问题。\n\n材料：毛泽东指出：“重工业是我国建设的重点，必须优先发展。但是绝不可以因此忽视生活资料尤其是粮食的生产……多发展一些农业、轻工业，表面上看是少搞了一些重工业，实际上反而能够更好地发展重工业。”\n\n（1）材料反映了毛泽东对苏联工业化模式的什么态度？（5分）\n（2）运用矛盾分析法，说明应如何处理好重工业与农业、轻工业的关系？（10分）",
        "answer": "（1）态度：以苏为鉴，反思苏联片面强调重工业、忽视农业轻工业导致粮食短缺、市场紧张的弊端；在坚持重工业优先的前提下，探索符合中国国情的工业化道路，而非机械照搬苏联模式。（2）矛盾分析：①承认矛盾客观存在——重工业与农业、轻工业既对立又统一；②把握主导方面——重工业是重点必须优先发展，但忽视农业轻工业会制约重工业（养不活工人、缺原料市场）；③注重转化——多发展农业轻工业不是削弱重工业，而是通过积累资金、提供原料和市场，促进重工业更好发展，体现“以退为进”“欲取先予”的辩证法；④统筹兼顾——以农业为基础、工业为主导，农轻重为序，实现国民经济协调发展。",
        "hint": "先点明对苏联模式的态度，再用对立统一分析。",
        "explanation": "16.2.md第一大关系及以苏为鉴论述。",
        "scoring_criteria": ["对苏联模式态度（5分）", "矛盾分析法运用（10分）"],
    },
]

CH11 = [
    {
        "id": "q001", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "政治生活主题的根本转变"},
        "stem": "社会主义制度建立后，国家政治生活的主题转变为（　）。",
        "options": [
            "正确处理人民内部矛盾",
            "继续以阶级斗争为纲",
            "全面恢复资本主义",
            "对外扩张",
        ],
        "answer": 0,
        "hint": "大规模阶级斗争基本结束后的根本性转变。",
        "explanation": "A正确。16.2.md：制度建立后正确处理人民内部矛盾成为政治生活主题。B若仍用阶级斗争眼光处理所有问题会造成严重后果。",
    },
    {
        "id": "q002", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "经验教训"},
        "stem": "社会主义建设初步探索的教训之一，是必须从实际出发，（　）。",
        "options": [
            "建设规模和速度要与国力相适应",
            "越快越好，越大越好",
            "完全停止经济建设",
            "只搞政治运动不搞生产",
        ],
        "answer": 0,
        "hint": "教材112-116页经验教训。",
        "explanation": "A正确。16.1.md：必须从实际出发，建设规模和速度要与国力相适应。B是导致曲折的原因之一；C、D错误。",
    },
    {
        "id": "q003", "type": "single_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.1.md", "label": "社会主义建设探索曲折"},
        "stem": "1957年之后社会主义建设探索走过的弯路包括（　）。",
        "options": ["1958年大跃进", "1959年严重自然灾害", "1978年十一届三中全会", "1954年第一届全国人大"],
        "answer": 0,
        "hint": "3.1.md提及大跃进等探索曲折。",
        "explanation": "A正确。3.1.md：1957年后探索走过弯路，如1958年大跃进、1959年自然灾害等。B是自然灾害非政策本身；C是改革开放转折；D是制度建设成就。",
    },
    {
        "id": "q004", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "社会主义社会的基本矛盾"},
        "stem": "社会主义社会基本矛盾的性质是（　）。",
        "options": ["非对抗性，可通过制度自我完善解决", "对抗性，只能暴力解决", "不存在任何矛盾", "与资本主义社会完全相同"],
        "answer": 0,
        "hint": "与旧社会基本矛盾有根本不同。",
        "explanation": "A正确。16.1.md：基本矛盾非对抗性，可通过社会主义制度自我调整完善解决。",
    },
    {
        "id": "q005", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch12", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/12.1.md", "label": "科学评价毛泽东"},
        "stem": "1981年《关于建国以来党的若干历史问题的决议》对毛泽东错误的时间节点判断是（　）。",
        "options": [
            "错误主要发生在1956年之后",
            "1956年前已犯根本性错误",
            "一生没有任何错误",
            "所有错误都应归咎于个人",
        ],
        "answer": 0,
        "hint": "1956年前没有犯根本性错误。",
        "explanation": "A正确。12.1.md：错误发生在1956年之后；1956年前没有犯根本性错误，说明选择社会主义道路是正确的。B、C、D与决议不符。",
    },
    {
        "id": "q006", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "经济建设和国防建设的关系"},
        "stem": "毛泽东论及国防建设与经济建设关系时强调（　）。",
        "options": [
            "降低军政费用比重，多搞经济建设，国防才能有更大进步",
            "无限扩大军费，挤占一切建设资金",
            "取消一切国防建设",
            "国防建设可以脱离经济基础",
        ],
        "answer": 0,
        "hint": "真正想要原子弹就要多搞经济建设。",
        "explanation": "A正确。16.2.md：经济建设发展更快，国防才能有更大进步；降低军政费用、多搞经济建设。",
    },
    {
        "id": "q007", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "三线建设"},
        "stem": "“三线建设”是指（　）。",
        "options": [
            "1964年起在中西部13个省区进行的大规模国防、科技、工业和交通建设",
            "在沿海发达地区集中全部工业",
            "仅指农业合作化运动",
            "改革开放后设立的经济特区建设",
        ],
        "answer": 0,
        "hint": "以战备为指导思想。",
        "explanation": "A正确。16.1.md：1964年起中西部13省区三线建设。B、C、D均不符合。",
    },
    {
        "id": "q008", "type": "single_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch12", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/12.1.md", "label": "实事求是的拨乱反正功能"},
        "stem": "邓小平以实事求是精神评价毛泽东，要求（　）。",
        "options": [
            "把毛泽东的正确思想与错误思想区分开来",
            "全盘否定毛泽东和毛泽东思想",
            "坚持“两个凡是”不改错误",
            "否认社会主义道路选择",
        ],
        "answer": 0,
        "hint": "正确思想属于毛泽东思想，错误思想不属于。",
        "explanation": "A正确。12.1.md：实事求是要求区分正确与错误思想；既反对两个凡是，又反对全盘否定。",
    },
    {
        "id": "q009", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch09", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/9.1.md", "label": "农业改造的问题"},
        "stem": "《关于建国以来党的若干历史问题的决议》指出农业改造存在（　）。",
        "options": ["要求过急、工作过粗、改变过快", "完全没有问题", "应当永不合作化", "由农民自发暴力没收土地"],
        "answer": 0,
        "hint": "速度过快是核心问题。",
        "explanation": "A正确。9.1.md/ch09-examples：存在要求过急、工作过粗、改变过快等问题。B、C、D错误。",
    },
    {
        "id": "q010", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "中国与外国关系的核心立场"},
        "stem": "《论十大关系》中处理中国和外国的关系，方针是（　）。",
        "options": [
            "有分析有批判地学习外国一切真正好的东西，不能盲目照抄",
            "闭关锁国拒绝一切外来事物",
            "全盘照搬西方制度",
            "只学政治不学科技",
        ],
        "answer": 0,
        "hint": "洋为中用，走自己的路。",
        "explanation": "A正确。16.2.md第十关系：一切民族国家的长处都要学，但有分析有批判，不能机械搬运。",
    },
    {
        "id": "q011", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch08", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/8.2.md", "label": "斯大林模式"},
        "stem": "照搬苏联模式在农业上的弊端之一，是（　）。",
        "options": ["片面强调重工业导致农业和轻工业长期滞后", "农业产值超过工业", "完全放弃工业化", "立即实现农业机械化"],
        "answer": 0,
        "hint": "16.2.md背景：照搬苏联暴露问题。",
        "explanation": "A正确。16.2.md：照搬苏联片面强调重工业，农业轻工业滞后等。B、C、D与史实相反。",
    },
    {
        "id": "q012", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "国际战略和外交工作"},
        "stem": "“三个世界”划分中，第三世界包括（　）。",
        "options": [
            "亚洲（除日本外）、非洲、拉丁美洲",
            "美国和苏联",
            "日本、欧洲、加拿大",
            "仅指中国",
        ],
        "answer": 0,
        "hint": "美苏第一世界，发达国家第二世界。",
        "explanation": "A正确。16.1.md：第三世界是亚非拉广大发展中国家。B是第一世界；C是第二世界；D片面。",
    },
    {
        "id": "q013", "type": "single_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch12", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/12.3.md", "label": "中苏关系四十年演变"},
        "stem": "邓小平1989年会见戈尔巴乔夫时总结中苏关系实质问题是（　）。",
        "options": ["不平等，中国人感到屈辱", "中国应永远依附苏联", "苏联从未影响中国", "中苏从未结盟"],
        "answer": 0,
        "hint": "“结束过去，开辟未来”八个字。",
        "explanation": "A正确。12.3.md：邓小平指出实质问题是不平等。B、C、D与四十年中苏关系史相反。",
    },
    {
        "id": "q014", "type": "single_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "执政党的建设"},
        "stem": "党在社会主义条件下强调加强执政党建设，反对的主要不良倾向不包括（　）。",
        "options": ["官僚主义、主观主义、宗派主义", "密切联系群众", "骄傲自满脱离群众", "忽视自身建设"],
        "answer": 1,
        "hint": "密切联系群众是要坚持的好作风。",
        "explanation": "B正确（选不包括）。16.1.md：反对官僚主义、主观主义、宗派主义，强调密切联系群众。B是应坚持的，不是不良倾向。",
    },
    {
        "id": "q015", "type": "single_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch12", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/12.1.md", "label": "功大于过"},
        "stem": "邓小平评价毛泽东“功过”关系时指出（　）。",
        "options": ["功绩第一位，错误第二位", "错误第一位，功绩第二位", "只有过没有功", "只有功没有过"],
        "answer": 0,
        "hint": "1980年接受法拉奇采访。",
        "explanation": "A正确。12.1.md：功是第一位，过是第二位。B、C、D与评价不符。",
    },
    # multiples
    {
        "id": "q016", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "经验教训"},
        "stem": "初步探索曲折的经验教训包括（　）。",
        "options": [
            "必须发展社会主义民主，健全社会主义法制",
            "必须坚持党的民主集中制和集体领导",
            "必须坚持对外开放",
            "可以关起门来搞建设",
            "必须正确认识主要矛盾，集中力量发展生产力",
        ],
        "answer": [0, 1, 2, 4],
        "hint": "六条教训系统概括。",
        "explanation": "ABCE正确。16.1.md六条。D与“必须坚持对外开放”相反。",
    },
    {
        "id": "q017", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "矛盾分析法的方法论意义"},
        "stem": "毛泽东运用矛盾分析法的方法论要点包括（　）。",
        "options": [
            "承认矛盾的客观性",
            "区分矛盾的性质",
            "善于抓住主要矛盾",
            "注重矛盾双方的转化",
            "回避一切矛盾",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "16.2.md四点方法论意义。",
        "explanation": "ABCD正确。16.2.md。E与“承认矛盾客观性”相反。",
    },
    {
        "id": "q018", "type": "multiple_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch12", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/12.1.md", "label": "科学评价毛泽东"},
        "stem": "十一届六中全会决议对毛泽东的科学评价要点包括（　）。",
        "options": [
            "功大于过，功绩第一位",
            "错误主要发生在1956年之后",
            "1956—1966年成就和错误是党中央集体领导结果",
            "错误责任全归毛泽东个人",
            "1956年前没有犯根本性错误",
        ],
        "answer": [0, 1, 2, 4],
        "hint": "责任具有集体性。",
        "explanation": "ABCE正确。12.1.md评价表。D与“责任集体性”相反。",
    },
    {
        "id": "q019", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch09", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/ch09-examples.md", "label": "社会主义改造的评价"},
        "stem": "《决议》指出的社会主义改造存在问题包括（　）。",
        "options": ["要求过急", "工作过粗", "改变过快", "形式过于单一简单化", "根本不应进行改造"],
        "answer": [0, 1, 2, 3],
        "hint": "ch09-examples五个问题。",
        "explanation": "ABCD正确。ch09-examples引决议五方面问题。E与“成功”“了不起”评价矛盾。",
    },
    {
        "id": "q020", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "历史背景"},
        "stem": "《论十大关系》发表的背景因素包括（　）。",
        "options": [
            "1956年苏共二十大反思斯大林问题",
            "社会主义改造基本完成",
            "照搬苏联模式暴露弊端",
            "改革开放已经启动",
            "大规模社会主义建设即将展开",
        ],
        "answer": [0, 1, 2, 4],
        "hint": "1956年是关键转折点。",
        "explanation": "ABCE正确。16.2.md历史背景。D是1978年后。",
    },
    {
        "id": "q021", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch08", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/8.2.md", "label": "战时共产主义政策"},
        "stem": "苏联探索中对中国的教训包括（　）。",
        "options": [
            "战时共产主义引发强烈反对",
            "新经济政策说明小农国家不能直接过渡到共产主义",
            "斯大林模式20年完成工业化有借鉴意义",
            "应机械照搬余粮收集制",
            "列宁提出社会主义可借鉴资本主义先进管理制度",
        ],
        "answer": [0, 1, 2, 4],
        "hint": "正反两方面经验。",
        "explanation": "ABCE正确。8.2.md苏联三阶段+斯大林模式。D是应该避免的教训。",
    },
    {
        "id": "q022", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "和平共处五项基本原则"},
        "stem": "和平共处五项原则包括（　）。",
        "options": [
            "互相尊重主权和领土完整",
            "互不侵犯",
            "互不干涉内政",
            "平等互利",
            "军事同盟对抗第三国",
        ],
        "answer": [0, 1, 2, 3],
        "hint": "第五项是和平共处。",
        "explanation": "ABCD正确。16.1.md五项原则前四项，还有和平共处。E不是五项原则内容。",
    },
    {
        "id": "q023", "type": "multiple_choice", "difficulty": "hard",
        "source": "review", "sourceChapter": "ch12", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/12.3.md", "label": "独立自主在外交中的核心要求"},
        "stem": "独立自主外交原则的核心要求包括（　）。",
        "options": [
            "不允许干涉内政",
            "与所有国家建立平等关系",
            "平等地位要靠自己争取",
            "可以牺牲主权换取援助",
            "涉及主权绝不让步",
        ],
        "answer": [0, 1, 2, 4],
        "hint": "半个手指头都不行。",
        "explanation": "ABCE正确。12.3.md三项核心要求及毛泽东、邓小平主权立场。D与主权底线相反。",
    },
    {
        "id": "q024", "type": "multiple_choice", "difficulty": "medium",
        "source": "review", "sourceChapter": "ch16", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "国家、生产单位和生产者个人的关系"},
        "stem": "《论十大关系》论及国家、集体、个人关系时强调（　）。",
        "options": [
            "不能只顾一头，必须兼顾三方面利益",
            "不能像苏联那样把农民挖得很苦",
            "工厂、合作社与生产者个人关系都要处理好",
            "只强调国家不顾个人",
            "只强调个人不顾国家",
        ],
        "answer": [0, 1, 2],
        "hint": "第四大关系。",
        "explanation": "ABC正确。16.2.md第四关系。D、E片面。",
    },
    {
        "id": "q025", "type": "multiple_choice", "difficulty": "basic",
        "source": "review", "sourceChapter": "ch03", "points": 2,
        "sourceRef": {"path": "content/maogai/detail/3.2.md", "label": "各阶段的核心论断"},
        "stem": "社会主义革命和建设时期的核心论断包括（　）。",
        "options": [
            "实现了最为广泛而深刻的社会变革",
            "东方大国大步迈进社会主义社会",
            "实现了从温饱不足到全面小康",
            "为中华民族伟大复兴奠定根本政治前提和制度基础",
            "彻底结束了半殖民地半封建社会历史",
        ],
        "answer": [0, 1, 3],
        "hint": "区分不同历史时期论断。",
        "explanation": "ABD正确。3.2.md社会主义革命和建设时期两个“实现了”。C是改革开放时期；E是新民主主义革命时期。",
    },
    # essays
    {
        "id": "q026", "type": "essay", "difficulty": "basic", "label": "简答题",
        "source": "review", "sourceChapter": "ch16", "points": 10, "total_points": 10,
        "sourceRef": {"path": "content/maogai/detail/16.1.md", "label": "经验教训"},
        "stem": "简述社会主义建设道路初步探索的主要经验教训（至少四条）。",
        "answer": "①必须把马克思主义与中国实际相结合，探索符合中国国情的社会主义建设道路。②必须正确认识社会主义社会主要矛盾和根本任务，集中力量发展生产力。③必须从实际出发，建设规模和速度要与国力相适应。④必须发展社会主义民主，健全社会主义法制。⑤必须坚持党的民主集中制和集体领导，加强执政党建设。⑥必须坚持对外开放，不能关起门来搞建设。",
        "hint": "教材112-116页六条。",
        "explanation": "16.1.md系统总结，是理解探索曲折的关键。",
        "scoring_criteria": ["每条2.5分，答出四条即满分"],
    },
    {
        "id": "q027", "type": "essay", "difficulty": "medium", "label": "简答题",
        "source": "review", "sourceChapter": "ch12", "points": 10, "total_points": 10,
        "sourceRef": {"path": "content/maogai/detail/12.1.md", "label": "两个30年的关系"},
        "stem": "简述如何正确看待改革开放前后两个历史时期的关系。",
        "answer": "①不能相互否定：不能用改革开放后时期否定改革开放前时期，也不能用前者否定后者。②共同主题：都是党领导人民进行社会主义建设的艰辛探索。③前者为后者积累条件：如50—70年代外交突破（中法建交、中美关系改善等）为改革开放后面向西方学习开放准备了政治条件。④后者是对前者的坚持、改革和发展：如不结盟政策、伙伴关系政策是在前期外交探索基础上的发展。⑤两个时期一脉相承又与时俱进，本质上都是社会主义建设实践。",
        "hint": "ch12-examples例题3及16.1.md两个30年。",
        "explanation": "综合12.1/ch12-examples与16.1.md。",
        "scoring_criteria": ["不可相互否定（2分）", "共同主题（2分）", "积累条件举例（3分）", "继承发展（3分）"],
    },
    {
        "id": "q028", "type": "essay", "difficulty": "hard", "label": "论述题",
        "source": "review", "sourceChapter": "ch16", "points": 15, "total_points": 15,
        "sourceRef": {"path": "content/maogai/detail/16.2.md", "label": "人民内部矛盾：社会主义社会的政治主题"},
        "stem": "论述社会主义制度建立后，正确处理人民内部矛盾的理论内容及其意义，并说明若背离这一理论可能造成的后果。",
        "answer": "理论内容：社会主义基本矛盾仍是生产力与生产关系、经济基础与上层建筑的矛盾，但属非对抗性，可通过制度自我完善解决。1956年八大指出主要矛盾是人民对先进工业国和经济文化迅速发展的需要同落后现实之间的矛盾，根本任务是发展生产力。毛泽东系统区分敌我矛盾（对抗性、专政方法）与人民内部矛盾（非对抗性、民主方法、团结—批评—团结），并针对不同领域提出统筹兼顾、百花齐放、长期共存等方针。制度建立后，正确处理人民内部矛盾成为政治生活主题，标志着从革命时期以阶级斗争为主题的根本转变。意义：为探索社会主义建设提供政治保障和理论工具，避免将大量人民内部矛盾误作敌我矛盾。背离后果：16.2.md指出，若仍用阶级斗争眼光看待所有问题，会把人民内部矛盾当作敌我矛盾处理，造成严重后果——这恰是后来探索曲折的重要分析框架。",
        "hint": "理论+主题转变+意义+背离后果。",
        "explanation": "16.1.md矛盾学说+16.2.md政治主题转变。",
        "scoring_criteria": ["基本矛盾与主要矛盾（4分）", "两类矛盾与方法（4分）", "政治主题转变（3分）", "意义与背离后果（4分）"],
    },
    {
        "id": "q029", "type": "essay", "difficulty": "hard", "label": "材料分析题",
        "source": "review", "sourceChapter": "ch03", "points": 15, "total_points": 15,
        "sourceRef": {"path": "content/maogai/detail/3.1.md", "label": "社会主义建设探索曲折"},
        "stem": "阅读材料，回答问题。\n\n材料：教材指出，1957年之后社会主义建设探索也走过一些弯路，如1958年大跃进、1959年严重自然灾害等。1981年《决议》既肯定初步探索的独创性理论成果和巨大成就，也总结了包括“建设规模和速度要与国力相适应”在内的经验教训。习近平强调：对毛泽东同志的评价应放在其所处时代和社会历史条件下去认识。\n\n（1）应如何历史唯物主义地看待这段探索中的成就与曲折？（8分）\n（2）这一认识对今天坚持和发展中国特色社会主义有何启示？（7分）",
        "answer": "（1）历史唯物主义态度：①把探索放在经济文化落后大国建设社会主义的具体国情和时代条件下理解，不能用今天标准苛求前人。②肯定1956年前选择社会主义道路的正确性，以及初步探索在制度巩固、工业体系建立、理论成果（如《论十大关系》、两类矛盾学说）方面的巨大成就，为改革开放提供经验、理论准备和物质基础。③同时正视1957年后如大跃进等弯路，分析原因——包括脱离实际、规模速度超出国力、未能始终正确处理人民内部矛盾等（16.1.md经验教训）。④1981年《决议》和实事求是评价毛泽东体现了辩证态度：功大于过，区分毛泽东正确思想与错误思想。（2）启示：①必须坚持马克思主义与中国实际相结合，走自己的路（独立自主）。②必须坚持以经济建设为中心、发展生产力。③必须从国情出发确定建设规模和速度。④坚持对外开放，借鉴人类优秀文明成果。⑤两个历史时期不能相互否定，要在继承中改革发展。",
        "hint": "成就+曲折+评价方法+当代启示。",
        "explanation": "综合3.1.md、16.1.md、12.1.md科学评价精神。",
        "scoring_criteria": ["历史唯物主义评价成就与曲折（8分）", "当代启示（7分）"],
    },
]
