import type { ContentItem } from '@/lib/types/content';

/**
 * 毛泽东思想和中国特色社会主义理论体系概论 · 详解分类内容
 * 16 章数据（12 章有源材料，4 章 stub）。
 * 基于 12 次课堂录音整合。
 */
export const maogaiDetailItems: ContentItem[] = [
  {
    id: 'ch01',
    title: '马克思主义中国化导论',
    type: 'section',
    status: 'done',
    summary:
      '课程介绍与教学安排；马克思主义中国化命题的提出；毛泽东思想与中国特色社会主义理论体系的关系。',
    children: [
      {
        id: '1.1',
        title: '课程介绍与教学安排',
        type: 'section',
        status: 'done',
        summary: '课程名称解析（毛泽东思想和中国特色社会主义理论体系概论）；教学安排（17周+3个晚上共40学时）；课程内容主线（马克思主义中国化的理论成果）。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '1.2',
        title: '马克思主义中国化命题',
        type: 'section',
        status: 'done',
        summary: '马克思主义中国化的内涵；毛泽东思想是马克思主义中国化第一次历史性飞跃的理论成果；中国特色社会主义理论体系是马克思主义中国化最新成果。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch02',
    title: '马克思主义中国化的历史进程',
    type: 'section',
    status: 'done',
    summary:
      '马克思主义中国化命题的正式提出；长征与遵义会议；第五次反围剿失败的教训；照搬苏联本本的错误。',
    children: [
      {
        id: '2.1',
        title: '马克思主义中国化命题的提出',
        type: 'section',
        status: 'done',
        summary: '第五次反围剿失败的教训；照搬苏联本本的错误；遵义会议的历史转折意义；六届六中全会正式提出马克思主义中国化命题。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '2.2',
        title: '长征与遵义会议',
        type: 'section',
        status: 'done',
        summary: '红军长征的背景（第五次反围剿失败）；遵义会议的内容与意义（纠正军事指挥错误、确立毛泽东领导地位）；长征精神的历史意义。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch03',
    title: '毛泽东思想及其历史地位',
    type: 'section',
    status: 'done',
    summary:
      '毛泽东思想的科学内涵；毛泽东思想的形成和发展过程；毛泽东思想的历史地位与指导意义。',
    children: [
      {
        id: '3.1',
        title: '毛泽东思想的形成和发展',
        type: 'section',
        status: 'done',
        summary: '毛泽东思想形成的社会历史条件；马克思主义中国化的第一次历史性飞跃；从新民主主义革命到社会主义建设的理论探索。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '3.2',
        title: '毛泽东思想的主要内容',
        type: 'section',
        status: 'done',
        summary: '新民主主义革命理论；社会主义革命和社会主义建设理论；革命军队建设和军事战略理论；政策和策略理论；思想政治工作和文化工作理论；党的建设理论。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '3.3',
        title: '毛泽东思想的历史地位',
        type: 'section',
        status: 'done',
        summary: '毛泽东思想是马克思主义中国化第一次历史性飞跃的理论成果；毛泽东思想是中国革命和建设的科学指南；毛泽东思想是中国共产党和中国人民的宝贵精神财富。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch04',
    title: '新民主主义革命理论——历史条件',
    type: 'section',
    status: 'done',
    summary:
      '近代中国国情（半殖民地半封建社会）；近代中国革命的历史任务；新民主主义革命理论的形成。',
    children: [
      {
        id: '4.1',
        title: '近代中国国情与革命任务',
        type: 'section',
        status: 'done',
        summary: '鸦片战争后中国社会性质的变化；半殖民地半封建社会的基本特点；帝国主义和中华民族的矛盾、封建主义和人民大众的矛盾。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '4.2',
        title: '新民主主义革命的总路线',
        type: 'section',
        status: 'done',
        summary: '无产阶级领导的、人民大众的、反对帝国主义、封建主义和官僚资本主义的革命；革命的对象、动力、领导力量和性质。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch05',
    title: '新民主主义革命理论——革命理论',
    type: 'section',
    status: 'done',
    summary:
      '政治革命理论框架（主体、条件、形式、结果）；法国大革命、十月革命、辛亥革命比较分析；新民主主义革命的独特性。',
    children: [
      {
        id: '5.1',
        title: '政治革命理论框架',
        type: 'section',
        status: 'done',
        summary: '政治革命的四个分析维度：革命主体、革命条件、革命形式、革命结果；法国大革命（资产阶级民主革命）、十月革命（社会主义革命）的比较分析。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '5.2',
        title: '新旧民主主义革命比较',
        type: 'section',
        status: 'done',
        summary: '辛亥革命（旧民主主义革命）的分析；新民主主义革命的"新"在哪里（新道路、新合作、新前途）；革命领导权的关键意义。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch06',
    title: '新民主主义革命理论——革命道路',
    type: 'section',
    status: 'stub',
    summary: '无课堂录音源材料。计划涵盖农村包围城市、武装夺取政权的革命道路理论。',
    children: [],
  },
  {
    id: 'ch07',
    title: '新民主主义革命理论——三大法宝',
    type: 'section',
    status: 'done',
    summary:
      '统一战线、武装斗争、党的建设；毛泽东《中国社会各阶级的分析》；农村包围城市道路的实践基础。',
    children: [
      {
        id: '7.1',
        title: '统一战线',
        type: 'section',
        status: 'done',
        summary: '建立统一战线的必要性；统一战线中的两个联盟；统一战线的策略原则；不同时期统一战线的特点。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '7.2',
        title: '武装斗争',
        type: 'section',
        status: 'done',
        summary: '武装斗争是中国革命的主要形式；人民军队建设思想；游击战争的战略地位；武装斗争与农村包围城市道路的关系。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '7.3',
        title: '党的建设',
        type: 'section',
        status: 'done',
        summary: '中国共产党建设的特殊环境；思想建党、政治建军；毛泽东《中国社会各阶级的分析》的阶级分析方法；党的建设与统一战线、武装斗争的关系。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch08',
    title: '社会主义改造理论（上）',
    type: 'section',
    status: 'done',
    summary:
      '新民主主义社会的过渡性质；过渡时期总路线的提出；从新民主主义向社会主义过渡的历史条件。',
    children: [
      {
        id: '8.1',
        title: '新民主主义社会',
        type: 'section',
        status: 'done',
        summary: '新民主主义社会的性质（过渡性的社会）；新民主主义社会的经济成分（五种经济成分）；新民主主义社会的阶级构成。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '8.2',
        title: '过渡时期总路线',
        type: 'section',
        status: 'done',
        summary: '过渡时期总路线的内容（一化三改）；从新民主主义向社会主义过渡的历史必然性；过渡时期总路线的特点（社会主义工业化与社会主义改造同时并举）。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch09',
    title: '社会主义改造理论（下）',
    type: 'section',
    status: 'done',
    summary:
      '农业、手工业的社会主义改造；资本主义工商业的社会主义改造（和平赎买）；社会主义基本制度的确立。',
    children: [
      {
        id: '9.1',
        title: '农业社会主义改造',
        type: 'section',
        status: 'done',
        summary: '农业合作化的步骤（互助组→初级社→高级社）；自愿互利、典型示范、国家帮助的原则；苏联农业集体化的经验教训。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '9.2',
        title: '手工业社会主义改造',
        type: 'section',
        status: 'done',
        summary: '手工业合作化的步骤和形式；供销合作小组→供销合作社→生产合作社。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '9.3',
        title: '资本主义工商业社会主义改造',
        type: 'section',
        status: 'done',
        summary: '和平赎买政策的理论依据和实践；国家资本主义的多种形式（加工订货→统购包销→公私合营）；社会主义基本制度在中国的确立。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch10',
    title: '社会主义建设道路的初步探索',
    type: 'section',
    status: 'stub',
    summary: '无课堂录音源材料。计划涵盖《论十大关系》、社会主义社会基本矛盾理论。',
    children: [],
  },
  {
    id: 'ch11',
    title: '社会主义建设的曲折发展',
    type: 'section',
    status: 'stub',
    summary: '无课堂录音源材料。计划涵盖"大跃进"、人民公社化运动、文化大革命等历史事件。',
    children: [],
  },
  {
    id: 'ch12',
    title: '毛泽东思想活的灵魂',
    type: 'section',
    status: 'done',
    summary:
      '实事求是、群众路线、独立自主；改革开放前后两个30年的关系；不结盟政策与独立自主外交。',
    children: [
      {
        id: '12.1',
        title: '实事求是',
        type: 'section',
        status: 'done',
        summary: '实事求是的内涵（一切从实际出发，理论联系实际，在实践中检验和发展真理）；实事求是是毛泽东思想的精髓；实事求是与教条主义的根本区别。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '12.2',
        title: '群众路线',
        type: 'section',
        status: 'done',
        summary: '群众路线的内容（一切为了群众，一切依靠群众，从群众中来，到群众中去）；群众路线是党的根本工作路线；群众路线的历史意义与现实价值。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '12.3',
        title: '独立自主',
        type: 'section',
        status: 'done',
        summary: '独立自主的内涵（坚持独立思考，走自己的路）；独立自主与对外开放的关系；不结盟政策；改革开放前后两个30年的辩证关系。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch13',
    title: '邓小平理论（上）',
    type: 'section',
    status: 'stub',
    summary: '无课堂录音源材料。计划涵盖邓小平理论的形成背景和基本问题。',
    children: [],
  },
  {
    id: 'ch14',
    title: '邓小平理论（下）',
    type: 'section',
    status: 'done',
    summary:
      '社会主义初级阶段理论；党的基本路线；社会主义市场经济体制；改革开放的理论与实践。',
    children: [
      {
        id: '14.1',
        title: '社会主义初级阶段理论',
        type: 'section',
        status: 'done',
        summary: '社会主义初级阶段的含义和特征；党的基本路线（一个中心、两个基本点）；"姓社姓资"争论与邓小平南方讲话。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '14.2',
        title: '改革开放理论',
        type: 'section',
        status: 'done',
        summary: '改革是中国的第二次革命；社会主义市场经济体制的确立；家庭联产承包责任制；经济特区建设；政治体制改革。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch15',
    title: '"一国两制"与祖国统一',
    type: 'section',
    status: 'done',
    summary:
      '"一国两制"构想的形成与实践；香港澳门回归；台湾问题与和平统一方针；对外关系与和平共处五项原则。',
    children: [
      {
        id: '15.1',
        title: '"一国两制"构想',
        type: 'section',
        status: 'done',
        summary: '"一国两制"构想的提出背景和内涵；香港、澳门回归的实践；"一国两制"的历史意义。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '15.2',
        title: '祖国统一与对外关系',
        type: 'section',
        status: 'done',
        summary: '台湾问题的历史由来；"江八条"与和平统一方针；和平共处五项原则；经济全球化与中国外交战略。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch16',
    title: '期末复习与重点梳理',
    type: 'section',
    status: 'done',
    summary:
      '全课程重点知识梳理；论十大关系；社会主义社会基本矛盾与主要矛盾；两类矛盾学说；四个现代化。',
    children: [
      {
        id: '16.1',
        title: '重点知识梳理',
        type: 'section',
        status: 'done',
        summary: '全课程核心概念和理论梳理；各章节重点和难点回顾；考试重点提示。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '16.2',
        title: '论十大关系与矛盾分析',
        type: 'section',
        status: 'done',
        summary: '《论十大关系》的核心思想；社会主义社会基本矛盾（生产力与生产关系、经济基础与上层建筑）；社会主义社会主要矛盾；两类不同性质的矛盾；四个现代化目标。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
];

/** 各章录音文件映射（12 个章有录音，4 个 stub 章无录音） */
export const maogaiRecordings: Record<string, string[]> = {
  ch01: ['毛概-第一二节-学习计划与安排.txt'],
  ch02: ['毛概-第二节-含重要通知.txt'],
  ch03: ['第三节毛泽东思想及毛泽东个人介绍课程.txt'],
  ch04: ['毛概-第四节.txt'],
  ch05: ['毛概-第五节.txt'],
  ch07: ['毛概第七节（有划重点）.txt'],
  ch08: ['毛概第八节-社会主义改造理论与过渡路线分析.txt'],
  ch09: ['毛概第9节.txt'],
  ch12: ['第12节毛泽东思想与邓小平理论讲解.txt'],
  ch14: ['毛概第14节.txt'],
  ch15: ['第15节毛概.txt'],
  ch16: ['毛概补充课（有划重点）.txt'],
};
