import type { ContentItem } from '@/lib/types/content';

/**
 * 中国近现代史纲要 · 详解分类内容
 * 10 章完整数据，每章含 sections、summary。
 * 基于 10 次课堂录音整合。
 */
export const modernHistoryDetailItems: ContentItem[] = [
  {
    id: 'ch01',
    title: '课程导论：历史观与方法论',
    type: 'section',
    status: 'done',
    summary:
      '课程性质与教学目标；历史学习的功能与意义；唯物史观与科学历史观；四个选择；历史虚无主义的批判。',
    children: [
      {
        id: '1.1',
        title: '课程意义与教学安排',
        type: 'section',
        status: 'done',
        summary: '课程性质（政治理论课）；历史学习的资政育人功能；历史的三个特点（一次性、相似性、规律性）；学史明理、爱党爱国的教育目标。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '1.2',
        title: '科学历史观与方法论',
        type: 'section',
        status: 'done',
        summary: '四个选择（马克思主义、中国共产党、社会主义道路、改革开放）；唯物史观与正确党史观；历史虚无主义的典型表现与批判；近现代史的主题主线（中华民族伟大复兴）。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch02',
    title: '对国家出路的早期探索：农民阶级',
    type: 'section',
    status: 'done',
    summary:
      '太平天国运动的经济背景（银荒与末世）；洪秀全与拜上帝教；太平天国的兴起、制度与失败。',
    children: [
      {
        id: '2.1',
        title: '太平天国的背景：银荒与末世',
        type: 'section',
        status: 'done',
        summary: '清中叶的财政危机；银铜双本位制与银贵钱贱；火耗归公与苛捐杂税；鸦片战争后社会矛盾的激化。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '2.2',
        title: '洪秀全与拜上帝教',
        type: 'section',
        status: 'done',
        summary: '洪秀全的科举之路与丁酉异梦；《劝世良言》与基督教的本土化改造；冯云山与紫荆山区的传教活动；拜上帝教的思想来源。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '2.3',
        title: '太平天国运动的兴起与失败',
        type: 'section',
        status: 'done',
        summary: '金田起义与定都天京；《天朝田亩制度》与《资政新篇》；太平天国的内部分裂；农民阶级的历史局限性。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch03',
    title: '对国家出路的早期探索：地主阶级洋务派',
    type: 'section',
    status: 'done',
    summary:
      '洋务运动的背景与指导思想；主要内容（军事、工业、教育）；历史评价与失败原因。',
    children: [
      {
        id: '3.1',
        title: '洋务运动的背景与指导思想',
        type: 'section',
        status: 'done',
        summary: '三千年未有之大变局；「中体西用」思想的形成；奕訢、曾国藩、李鸿章等洋务派代表人物。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '3.2',
        title: '洋务运动的主要内容',
        type: 'section',
        status: 'done',
        summary: '军事工业（江南制造总局等）；民用工业（轮船招商局等）；海防建设与新式海军；新式学堂与留学生派遣。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '3.3',
        title: '洋务运动的历史评价与失败原因',
        type: 'section',
        status: 'done',
        summary: '洋务运动的客观进步作用；甲午战败宣告洋务运动破产；「中体西用」的根本局限；地主阶级自救运动的历史命运。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch04',
    title: '对国家出路的早期探索：早期资产阶级与维新思想',
    type: 'section',
    status: 'done',
    summary:
      '早期维新思想家（王韬、郑观应）；甲午战败的思想冲击；维新派与守旧派的论战。',
    children: [
      {
        id: '4.1',
        title: '早期维新思想家：王韬与郑观应',
        type: 'section',
        status: 'done',
        summary: '王韬的宪政思想与「西学中源说」；郑观应的《盛世危言》与「商战」思想；从器物到制度的思想转变。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '4.2',
        title: '甲午战败与民族资本主义发展',
        type: 'section',
        status: 'done',
        summary: '甲午战争与《马关条约》；2.3亿两白银赔款的财政冲击；路矿权抵押与资本输出；民族资本主义的初步发展。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '4.3',
        title: '维新派与守旧派的论战',
        type: 'section',
        status: 'done',
        summary: '要不要变法；要不要兴民权、设议院；要不要废八股、改科举；论战的实质与历史意义。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch05',
    title: '戊戌变法的政治实践与辛亥革命的准备',
    type: 'section',
    status: 'done',
    summary:
      '百日维新的政治实践；戊戌变法的失败原因；辛亥革命的准备与革命团体的涌现。',
    children: [
      {
        id: '5.1',
        title: '百日维新的政治实践',
        type: 'section',
        status: 'done',
        summary: '明定国是诏；103天内100多道诏书；政治改革（裁汰冗员、改革行政机构）；经济与军事改革措施。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '5.2',
        title: '戊戌变法的失败原因',
        type: 'section',
        status: 'done',
        summary: '改革速度过快、缺乏可操作性；触动既得利益集团（旗人铁庄稼、冗员裁汰）；守旧势力的反扑；戊戌六君子与变法的历史意义。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '5.3',
        title: '辛亥革命的准备：革命团体的涌现',
        type: 'section',
        status: 'done',
        summary: '兴中会与华兴会等革命团体；资产阶级革命派与传统地下会社的结合；革命方法论的探索。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch06',
    title: '辛亥革命与民国初年政局',
    type: 'section',
    status: 'done',
    summary:
      '中国同盟会的成立与三民主义；辛亥革命与中华民国的建立；民国初年政局与二次革命。',
    children: [
      {
        id: '6.1',
        title: '中国同盟会的成立与三民主义',
        type: 'section',
        status: 'done',
        summary: '1905年中国同盟会的成立；「驱逐鞑虏、恢复中华、建立民国、平均地权」纲领；《民报》与三民主义的系统阐述；兴中会与同盟会的性质区别。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '6.2',
        title: '辛亥革命与中华民国的建立',
        type: 'section',
        status: 'done',
        summary: '武昌起义与各省响应；中华民国的建立；《中华民国临时约法》；袁世凯窃取革命果实。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '6.3',
        title: '民国初年政局与二次革命',
        type: 'section',
        status: 'done',
        summary: '袁世凯的独裁统治；宋教仁案与二次革命；护国运动与护法运动的失败；资产阶级共和国方案的破产。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch07',
    title: '五四运动与马克思主义的传播',
    type: 'section',
    status: 'done',
    summary:
      '新文化运动与国民性改造；十月革命与马克思主义的传播；五四运动与中国共产党的成立。',
    children: [
      {
        id: '7.1',
        title: '新文化运动与国民性改造',
        type: 'section',
        status: 'done',
        summary: '陈独秀与《新青年》杂志；「德先生」与「赛先生」；蔡元培与北京大学的改造；白话文运动；对传统文化的理性态度。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '7.2',
        title: '十月革命与马克思主义的传播',
        type: 'section',
        status: 'done',
        summary: '梁启超的「器物→制度→思想」公式；孙中山的先知先觉/后知后觉/无知无觉分类；马克思主义早期传入中国（1899年万国公报、1903年梁启超介绍）；十月革命对中国知识分子的震撼。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '7.3',
        title: '五四运动与中国共产党的成立',
        type: 'section',
        status: 'done',
        summary: '五四运动的爆发；工人阶级登上历史舞台；马克思主义的广泛传播；中国共产党成立的历史条件与意义。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch08',
    title: '第一次国共合作与大革命',
    type: 'section',
    status: 'done',
    summary:
      '中共二大与国共合作的酝酿；国民党一大与第一次国共合作；大革命的兴起与失败。',
    children: [
      {
        id: '8.1',
        title: '中共二大与国共合作的酝酿',
        type: 'section',
        status: 'done',
        summary: '中共一大的闭门倾向；二大的最低纲领（打倒列强、除军阀）；共产国际的指导与党内争论；西湖会议与党内合作方式的确立。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '8.2',
        title: '国民党一大与第一次国共合作',
        type: 'section',
        status: 'done',
        summary: '1924年国民党一大的召开；新三民主义的提出；共产党员以个人身份加入国民党；联俄联共扶助农工三大政策。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '8.3',
        title: '大革命的兴起与失败',
        type: 'section',
        status: 'done',
        summary: '五卅运动与省港大罢工；北伐战争的胜利进军；蒋介石的权力扩张；四一二与七一五政变；大革命失败的原因与教训。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch09',
    title: '抗日战争：两条路线与中流砥柱',
    type: 'section',
    status: 'done',
    summary:
      '抗日战争的全面爆发；正面战场与国民党的片面抗战路线；敌后战场与中共的全面抗战路线；抗日战争的胜利。',
    children: [
      {
        id: '9.1',
        title: '抗日战争的全面爆发',
        type: 'section',
        status: 'done',
        summary: '卢沟桥事变与全面抗战开始；抗日民族统一战线的形成；国共两党合作抗日。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '9.2',
        title: '正面战场与国民党的片面抗战路线',
        type: 'section',
        status: 'done',
        summary: '淞沪会战的政治动机（争取国际干预）；片面抗战路线（单纯依赖政府和正规军）；花园口决堤事件；长沙文夕大火；豫湘桂大溃败。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '9.3',
        title: '敌后战场与中共的全面抗战路线',
        type: 'section',
        status: 'done',
        summary: '全面抗战路线（动员和武装民众）；敌后抗日根据地的建设；游击战争的战略地位；中共成为抗日战争的中流砥柱。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '9.4',
        title: '抗日战争的胜利',
        type: 'section',
        status: 'done',
        summary: '战略相持阶段的到来；世界反法西斯战争的配合；日本投降与中国抗战的伟大胜利；抗日战争的历史意义。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
  {
    id: 'ch10',
    title: '解放战争与新中国成立',
    type: 'section',
    status: 'done',
    summary:
      '战后国际格局与国共谈判；解放战争的进程；中华人民共和国的成立。',
    children: [
      {
        id: '10.1',
        title: '战后国际格局与国共谈判',
        type: 'section',
        status: 'done',
        summary: '战后民族解放运动潮流；美国的对华政策（控制中国、遏制苏联）；杜鲁门与蒋介石的微妙关系；重庆谈判与双十协定。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '10.2',
        title: '解放战争的进程',
        type: 'section',
        status: 'done',
        summary: '国民党发动全面内战；战略防御、战略反攻、战略决战三大战役；国民党政权的全面崩溃。',
        videoIds: [],
        interactiveIds: [],
      },
      {
        id: '10.3',
        title: '中华人民共和国的成立',
        type: 'section',
        status: 'done',
        summary: '新政协会议与《共同纲领》；开国大典；新中国成立的历史意义；新民主主义革命胜利的基本经验。',
        videoIds: [],
        interactiveIds: [],
      },
    ],
  },
];

/** 各章录音文件映射 */
export const modernHistoryRecordings: Record<string, string[]> = {
  ch01: ['中国近现代史纲要-第一课-课程意义与安排.txt', '中国近现代史2课学习要点分析.txt'],
  ch02: ['纲要-第三节.txt'],
  ch03: ['近现代史纲要-第四节.txt'],
  ch04: ['纲要-第五节-戊戌变法思想背景及论战分析.txt'],
  ch05: ['纲要第六节戊戌变法与辛亥革命教学分析.txt'],
  ch06: ['纲要第七节辛亥革命相关知识教学分析.txt'],
  ch07: ['中国近现代史纲要-第9节-五四运动.txt'],
  ch08: ['第12章近现代史纲要.txt'],
  ch09: ['第14章抗日战争国共抗战策略分析.txt'],
  ch10: ['第15节近现代史纲要.txt'],
};
