import type { ContentTree } from '@/lib/types/content';
import { probabilityDetailItems, probabilityRecordings } from './probability-detail';
import { modernHistoryDetailItems, modernHistoryRecordings } from './modern-history-detail';
import { organicChemistryDetailItems } from './organic-chemistry-detail';
import { maogaiDetailItems } from './maogai-detail';
import { physicsDetailItems } from './physics-detail';

const examPlaceholderCategories = [
  {
    id: 'kaoqian-moni',
    name: '考前模拟',
    items: [
      { id: 'placeholder', title: '敬请期待', type: 'document' as const, status: 'stub' as const },
    ],
  },
  {
    id: 'shizhan-yanlian',
    name: '实战演练',
    items: [
      { id: 'placeholder', title: '敬请期待', type: 'document' as const, status: 'stub' as const },
    ],
  },
];

const chemistryKaoqianMoniItems = [
  { id: 'sim-01', title: '有机化学期末模拟试卷一', type: 'document' as const, status: 'done' as const },
  { id: 'sim-02', title: '有机化学期末模拟试卷二', type: 'document' as const, status: 'done' as const },
  { id: 'sim-03', title: '有机化学期末模拟试卷三', type: 'document' as const, status: 'done' as const },
  { id: 'real-01', title: '有机化学期末真题模拟卷（一）', type: 'document' as const, status: 'done' as const },
  { id: 'real-02', title: '有机化学期末真题模拟卷（二）', type: 'document' as const, status: 'done' as const },
  { id: 'real-03', title: '有机化学期末真题模拟卷（三）', type: 'document' as const, status: 'done' as const },
  { id: 'real-04', title: '华中科技大学有机化学期末真题（四）2021-2022', type: 'document' as const, status: 'done' as const },
  { id: 'real-05', title: '华中科技大学有机化学期末真题（五）2023-2024', type: 'document' as const, status: 'done' as const },
];

export const contentTree: ContentTree = {
  subjects: [
    {
      id: 'probability',
      name: '概率论与数理统计',
      icon: 'Calculator',
      categories: [
        {
          id: 'textbook',
          name: '教材',
          items: [
            { id: 'main-textbook', title: '概率论与数理统计（教材）', type: 'document', status: 'stub' },
          ],
        },
        {
          id: 'detail',
          name: '详解',
          items: probabilityDetailItems,
        },
        {
          id: 'recording',
          name: '课上录音',
          items: [
            { id: 'rec-01', title: '第一节·课程导论与概率史', type: 'document', status: 'done' },
            { id: 'rec-02', title: '第二节·事件代数与概率公理', type: 'document', status: 'done' },
            { id: 'rec-03', title: '第三节·条件概率与贝叶斯', type: 'document', status: 'done' },
            { id: 'rec-04', title: '第四节·离散随机变量与常见分布', type: 'document', status: 'done' },
            { id: 'rec-07', title: '第七节·正态分布与连续分布', type: 'document', status: 'done' },
            { id: 'rec-08', title: '第八节·多维随机变量与联合分布', type: 'document', status: 'done' },
            { id: 'rec-09', title: '第九节·边缘分布与条件分布', type: 'document', status: 'done' },
            { id: 'rec-10', title: '第十节·独立性与多维函数分布', type: 'document', status: 'done' },
            { id: 'rec-11', title: '第十一节·多维总结与期望引入', type: 'document', status: 'done' },
            { id: 'rec-12', title: '第十二节·期望性质与柯西不等式', type: 'document', status: 'done' },
            { id: 'rec-13', title: '第十三节·方差与标准化', type: 'document', status: 'done' },
            { id: 'rec-14', title: '第十四节·相关系数与大数定律', type: 'document', status: 'done' },
            { id: 'rec-15', title: '第十五节·大数定律与中心极限定理', type: 'document', status: 'done' },
            { id: 'rec-16', title: '第十六节·样本与抽样分布', type: 'document', status: 'done' },
            { id: 'rec-17', title: '第十七节·三大分布与分位点', type: 'document', status: 'done' },
          ],
        },
        {
          id: 'summary',
          name: '课堂纪要',
          items: [
            { id: 'sum-01', title: '第一节·课程导论与概率史', type: 'document', status: 'done' },
            { id: 'sum-02', title: '第二节·事件代数与概率公理', type: 'document', status: 'done' },
            { id: 'sum-03', title: '第三节·条件概率与贝叶斯', type: 'document', status: 'done' },
            { id: 'sum-04', title: '第四节·离散随机变量与常见分布', type: 'document', status: 'done' },
            { id: 'sum-07', title: '第七节·正态分布与连续分布', type: 'document', status: 'done' },
            { id: 'sum-08', title: '第八节·多维随机变量与联合分布', type: 'document', status: 'done' },
            { id: 'sum-09', title: '第九节·边缘分布与条件分布', type: 'document', status: 'done' },
            { id: 'sum-10', title: '第十节·独立性与多维函数分布', type: 'document', status: 'done' },
            { id: 'sum-11', title: '第十一节·多维总结与期望引入', type: 'document', status: 'done' },
            { id: 'sum-12', title: '第十二节·期望性质与柯西不等式', type: 'document', status: 'done' },
            { id: 'sum-13', title: '第十三节·方差与标准化', type: 'document', status: 'done' },
            { id: 'sum-14', title: '第十四节·相关系数与大数定律', type: 'document', status: 'done' },
            { id: 'sum-15', title: '第十五节·大数定律与中心极限定理', type: 'document', status: 'done' },
            { id: 'sum-16', title: '第十六节·样本与抽样分布', type: 'document', status: 'done' },
            { id: 'sum-17', title: '第十七节·三大分布与分位点', type: 'document', status: 'done' },
          ],
        },
        ...examPlaceholderCategories,
      ],
    },
    {
      id: 'physics',
      name: '大学物理',
      icon: 'Atom',
      categories: [
        { id: 'textbook', name: '教材', items: [{ id: 'main', title: '大学物理（教材）', type: 'document', status: 'stub' }] },
        { id: 'detail', name: '详解', items: physicsDetailItems },
        {
          id: 'recording',
          name: '课上录音',
          items: [
            { id: 'rec-01', title: '第一讲·导论与质点运动学', type: 'document', status: 'done' },
            { id: 'rec-02', title: '第二讲·运动学例题与牛顿运动定律', type: 'document', status: 'done' },
            { id: 'rec-03', title: '第三讲·理想流体与伯努利方程', type: 'document', status: 'done' },
            { id: 'rec-04', title: '第四讲·粘性流体、泊肃叶定律与简谐振动', type: 'document', status: 'done' },
            { id: 'rec-06', title: '第六讲·振动能量、合成、拍与阻尼受迫振动', type: 'document', status: 'done' },
            { id: 'rec-07', title: '第七讲·机械波与平面简谐波', type: 'document', status: 'done' },
            { id: 'rec-08', title: '第八讲·波的干涉、驻波与多普勒效应', type: 'document', status: 'done' },
            { id: 'rec-09', title: '第九讲·分子动理论与麦克斯韦速率分布', type: 'document', status: 'done' },
            { id: 'rec-10', title: '第十讲·平均自由程与液体表面现象', type: 'document', status: 'done' },
            { id: 'rec-11', title: '第十一讲·电场强度、电场线与电通量', type: 'document', status: 'done' },
            { id: 'rec-12', title: '第十二讲·高斯定理与电势', type: 'document', status: 'done' },
            { id: 'rec-13', title: '第十三讲·电势、等势面与电偶极子', type: 'document', status: 'done' },
            { id: 'rec-14', title: '第十四讲·稳恒磁场与毕奥-萨伐尔定律', type: 'document', status: 'done' },
            { id: 'rec-15', title: '第十五讲·安培环路定理与洛伦兹力', type: 'document', status: 'done' },
            { id: 'rec-16', title: '第十六讲·安培力、力矩与霍尔效应', type: 'document', status: 'done' },
            { id: 'rec-17', title: '第十七讲·电磁感应与动生感生电动势', type: 'document', status: 'done' },
            { id: 'rec-19', title: '第十九讲·感生电场与互感自感', type: 'document', status: 'done' },
            { id: 'rec-20', title: '第二十讲·麦克斯韦方程组与电磁波', type: 'document', status: 'done' },
            { id: 'rec-21', title: '第二十一讲·透镜成像与光学仪器', type: 'document', status: 'done' },
            { id: 'rec-22', title: '第二十二讲·相干性、光程差与杨氏双缝', type: 'document', status: 'done' },
            { id: 'rec-23', title: '第二十三讲·光的偏振与黑体辐射、光电效应', type: 'document', status: 'done' },
            { id: 'rec-24', title: '第二十四讲·康普顿效应、玻尔理论与德布罗意波', type: 'document', status: 'done' },
            { id: 'rec-25', title: '第二十五讲·不确定关系、波函数与薛定谔方程', type: 'document', status: 'done' },
            { id: 'rec-26', title: '第二十六讲·原子核、核衰变与核能', type: 'document', status: 'done' },
            { id: 'rec-27', title: '第二十七讲·X射线、激光及医学应用', type: 'document', status: 'done' },
          ],
        },
        {
          id: 'summary',
          name: '课堂纪要',
          items: [
            { id: 'sum-01', title: '第一讲·导论与质点运动学', type: 'document', status: 'done' },
            { id: 'sum-02', title: '第二讲·运动学例题与牛顿运动定律', type: 'document', status: 'done' },
            { id: 'sum-03', title: '第三讲·理想流体与伯努利方程', type: 'document', status: 'done' },
            { id: 'sum-04', title: '第四讲·粘性流体、泊肃叶定律与简谐振动', type: 'document', status: 'done' },
            { id: 'sum-06', title: '第六讲·振动能量、合成、拍与阻尼受迫振动', type: 'document', status: 'done' },
            { id: 'sum-07', title: '第七讲·机械波与平面简谐波', type: 'document', status: 'done' },
            { id: 'sum-08', title: '第八讲·波的干涉、驻波与多普勒效应', type: 'document', status: 'done' },
            { id: 'sum-09', title: '第九讲·分子动理论与麦克斯韦速率分布', type: 'document', status: 'done' },
            { id: 'sum-10', title: '第十讲·平均自由程与液体表面现象', type: 'document', status: 'done' },
            { id: 'sum-11', title: '第十一讲·电场强度、电场线与电通量', type: 'document', status: 'done' },
            { id: 'sum-12', title: '第十二讲·高斯定理与电势', type: 'document', status: 'done' },
            { id: 'sum-13', title: '第十三讲·电势、等势面与电偶极子', type: 'document', status: 'done' },
            { id: 'sum-14', title: '第十四讲·稳恒磁场与毕奥-萨伐尔定律', type: 'document', status: 'done' },
            { id: 'sum-15', title: '第十五讲·安培环路定理与洛伦兹力', type: 'document', status: 'done' },
            { id: 'sum-16', title: '第十六讲·安培力、力矩与霍尔效应', type: 'document', status: 'done' },
            { id: 'sum-17', title: '第十七讲·电磁感应与动生感生电动势', type: 'document', status: 'done' },
            { id: 'sum-19', title: '第十九讲·感生电场与互感自感', type: 'document', status: 'done' },
            { id: 'sum-20', title: '第二十讲·麦克斯韦方程组与电磁波', type: 'document', status: 'done' },
            { id: 'sum-21', title: '第二十一讲·透镜成像与光学仪器', type: 'document', status: 'done' },
            { id: 'sum-22', title: '第二十二讲·相干性、光程差与杨氏双缝', type: 'document', status: 'done' },
            { id: 'sum-23', title: '第二十三讲·光的偏振与黑体辐射、光电效应', type: 'document', status: 'done' },
            { id: 'sum-24', title: '第二十四讲·康普顿效应、玻尔理论与德布罗意波', type: 'document', status: 'done' },
            { id: 'sum-25', title: '第二十五讲·不确定关系、波函数与薛定谔方程', type: 'document', status: 'done' },
            { id: 'sum-26', title: '第二十六讲·原子核、核衰变与核能', type: 'document', status: 'done' },
            { id: 'sum-27', title: '第二十七讲·X射线、激光及医学应用', type: 'document', status: 'done' },
          ],
        },
        ...examPlaceholderCategories,
      ],
    },
    {
      id: 'chemistry',
      name: '有机化学',
      icon: 'FlaskConical',
      categories: [
        { id: 'textbook', name: '教材', items: [{ id: 'main', title: '有机化学（教材）', type: 'document', status: 'stub' }] },
        {
          id: 'detail',
          name: '详解',
          items: organicChemistryDetailItems,
        },
        {
          id: 'recording',
          name: '课上录音',
          items: [
            { id: 'rec-01', title: '第一讲·绪论', type: 'document', status: 'done' },
            { id: 'rec-02', title: '第二讲·分子极性·酸碱理论·官能团', type: 'document', status: 'done' },
            { id: 'rec-03', title: '第三讲·有机化合物的命名', type: 'document', status: 'done' },
            { id: 'rec-04', title: '第四讲·分子间作用力', type: 'document', status: 'done' },
            { id: 'rec-05', title: '第五讲·烷烃结构与自由基取代', type: 'document', status: 'done' },
            { id: 'rec-06', title: '第六讲·环烷烃构象与诱导效应', type: 'document', status: 'done' },
            { id: 'rec-07', title: '第七讲·共轭与超共轭效应', type: 'document', status: 'done' },
            { id: 'rec-08', title: '第八讲·环己烷构象与电子效应应用', type: 'document', status: 'done' },
            { id: 'rec-09', title: '第九讲·烯烃的加成反应', type: 'document', status: 'done' },
            { id: 'rec-10', title: '第十讲·烯烃氧化·炔烃·芳香性', type: 'document', status: 'done' },
            { id: 'rec-11', title: '第十一讲·芳香亲电取代与定位效应', type: 'document', status: 'done' },
            { id: 'rec-12', title: '第十二讲·立体化学与手性', type: 'document', status: 'done' },
            { id: 'rec-13', title: '第十三讲·烯烃炔烃加成综合', type: 'document', status: 'done' },
            { id: 'rec-14', title: '第十四讲·卤代烃亲核取代', type: 'document', status: 'done' },
            { id: 'rec-15', title: '第十五讲·消除反应与金属有机', type: 'document', status: 'done' },
            { id: 'rec-16', title: '第十六讲·醇酚醚', type: 'document', status: 'done' },
            { id: 'rec-17', title: '第十七讲·醛酮', type: 'document', status: 'done' },
            { id: 'rec-18', title: '第十九讲·羧酸及其衍生物', type: 'document', status: 'done' },
            { id: 'rec-19', title: '第二十一讲·芳香取代与重氮盐', type: 'document', status: 'done' },
            { id: 'rec-20', title: '第二十五讲·含氮化合物与杂环', type: 'document', status: 'done' },
          ],
        },
        {
          id: 'summary',
          name: '课堂纪要',
          items: [
            { id: 'sum-01', title: '第一讲纪要·绪论', type: 'document', status: 'done' },
            { id: 'sum-02', title: '第二讲纪要·酸碱理论与命名', type: 'document', status: 'done' },
            { id: 'sum-03', title: '第三讲纪要·命名', type: 'document', status: 'done' },
            { id: 'sum-04', title: '第四讲纪要·分子间作用力', type: 'document', status: 'done' },
            { id: 'sum-05', title: '第五讲纪要·烷烃', type: 'document', status: 'done' },
            { id: 'sum-06', title: '第六讲纪要·环烷烃构象与诱导效应', type: 'document', status: 'done' },
            { id: 'sum-07', title: '第七讲纪要·共轭与超共轭', type: 'document', status: 'done' },
            { id: 'sum-08', title: '第八讲纪要·环己烷构象与电子效应', type: 'document', status: 'done' },
            { id: 'sum-09', title: '第九讲纪要·烯烃加成', type: 'document', status: 'done' },
            { id: 'sum-10', title: '第十讲纪要·炔烃与芳香性', type: 'document', status: 'done' },
            { id: 'sum-11', title: '第十一讲纪要·芳香亲电取代', type: 'document', status: 'done' },
            { id: 'sum-12', title: '第十二讲纪要·立体化学与手性', type: 'document', status: 'done' },
            { id: 'sum-13', title: '第十三讲纪要·烯炔加成综合', type: 'document', status: 'done' },
            { id: 'sum-14', title: '第十四讲纪要·卤代烃亲核取代', type: 'document', status: 'done' },
            { id: 'sum-16', title: '第十六讲纪要·醇酚醚', type: 'document', status: 'done' },
            { id: 'sum-17', title: '第十七讲纪要·醛酮', type: 'document', status: 'done' },
            { id: 'sum-18', title: '第十九讲纪要·羧酸及衍生物', type: 'document', status: 'done' },
            { id: 'sum-19', title: '第二十一讲纪要·芳香取代与重氮盐', type: 'document', status: 'done' },
            { id: 'sum-20', title: '第二十五讲纪要·含氮化合物', type: 'document', status: 'done' },
          ],
        },
        {
          id: 'kaoqian-moni',
          name: '考前模拟',
          items: chemistryKaoqianMoniItems,
        },
        examPlaceholderCategories[1],
      ],
    },
    {
      id: 'modern-history',
      name: '中国近现代史纲要',
      icon: 'BookOpen',
      categories: [
        { id: 'textbook', name: '教材', items: [{ id: 'main', title: '中国近现代史纲要（教材）', type: 'document', status: 'stub' }] },
        {
          id: 'detail',
          name: '详解',
          items: modernHistoryDetailItems,
        },
        {
          id: 'recording',
          name: '课上录音',
          items: [
            { id: 'rec-01', title: '第一课·课程意义与安排', type: 'document', status: 'done' },
            { id: 'rec-02', title: '第三课·农民阶级（太平天国）', type: 'document', status: 'done' },
            { id: 'rec-03', title: '第四课·地主阶级洋务派', type: 'document', status: 'done' },
            { id: 'rec-04', title: '第五课·早期资产阶级与维新思想', type: 'document', status: 'done' },
            { id: 'rec-05', title: '第六课·戊戌变法政治实践', type: 'document', status: 'done' },
            { id: 'rec-06', title: '第七课·辛亥革命', type: 'document', status: 'done' },
            { id: 'rec-07', title: '第九课·五四运动', type: 'document', status: 'done' },
            { id: 'rec-08', title: '第十二课·国共合作与大革命', type: 'document', status: 'done' },
            { id: 'rec-09', title: '第十四课·抗日战争', type: 'document', status: 'done' },
            { id: 'rec-10', title: '第十五课·解放战争', type: 'document', status: 'done' },
          ],
        },
        {
          id: 'summary',
          name: '课堂纪要',
          items: [
            { id: 'sum-01', title: '第一课纪要·课程意义与安排', type: 'document', status: 'done' },
            { id: 'sum-02', title: '第三课纪要·农民阶级', type: 'document', status: 'done' },
            { id: 'sum-03', title: '第四课纪要·洋务派', type: 'document', status: 'done' },
            { id: 'sum-04', title: '第五课纪要·维新思想', type: 'document', status: 'done' },
            { id: 'sum-05', title: '第六课纪要·戊戌变法', type: 'document', status: 'done' },
            { id: 'sum-06', title: '第七课纪要·辛亥革命', type: 'document', status: 'done' },
            { id: 'sum-07', title: '第九课纪要·五四运动', type: 'document', status: 'done' },
            { id: 'sum-08', title: '第十二课纪要·国共合作', type: 'document', status: 'done' },
            { id: 'sum-09', title: '第十四课纪要·抗日战争', type: 'document', status: 'done' },
            { id: 'sum-10', title: '第十五课纪要·解放战争', type: 'document', status: 'done' },
          ],
        },
        ...examPlaceholderCategories,
      ],
    },
    {
      id: 'maogai',
      name: '毛泽东思想和中国特色社会主义理论体系概论',
      icon: 'Scale',
      categories: [
        { id: 'textbook', name: '教材', items: [{ id: 'main', title: '毛概（教材）', type: 'document', status: 'stub' }] },
        {
          id: 'detail',
          name: '详解',
          items: maogaiDetailItems,
        },
        {
          id: 'recording',
          name: '课上录音',
          items: [
            { id: 'rec-01', title: '第一二节·课程导论', type: 'document', status: 'done' },
            { id: 'rec-02', title: '第二节·马克思主义中国化历史进程', type: 'document', status: 'done' },
            { id: 'rec-03', title: '第三节·毛泽东思想及其历史地位', type: 'document', status: 'done' },
            { id: 'rec-04', title: '第四节·新民主主义革命历史条件', type: 'document', status: 'done' },
            { id: 'rec-05', title: '第五节·新民主主义革命理论', type: 'document', status: 'done' },
            { id: 'rec-06', title: '第七节·新民主主义革命三大法宝', type: 'document', status: 'done' },
            { id: 'rec-07', title: '第八节·社会主义改造理论（上）', type: 'document', status: 'done' },
            { id: 'rec-08', title: '第九节·社会主义改造理论（下）', type: 'document', status: 'done' },
            { id: 'rec-09', title: '第十二节·毛泽东思想活的灵魂', type: 'document', status: 'done' },
            { id: 'rec-10', title: '第十四节·邓小平理论', type: 'document', status: 'done' },
            { id: 'rec-11', title: '第十五节·一国两制与祖国统一', type: 'document', status: 'done' },
            { id: 'rec-12', title: '补充课·期末复习', type: 'document', status: 'done' },
          ],
        },
        {
          id: 'summary',
          name: '课堂纪要',
          items: [
            { id: 'sum-01', title: '第一二节纪要·课程导论', type: 'document', status: 'done' },
            { id: 'sum-02', title: '第二节纪要·马克思主义中国化历史进程', type: 'document', status: 'done' },
            { id: 'sum-03', title: '第三节纪要·毛泽东思想及其历史地位', type: 'document', status: 'done' },
            { id: 'sum-04', title: '第四节纪要·新民主主义革命历史条件', type: 'document', status: 'done' },
            { id: 'sum-05', title: '第五节纪要·新民主主义革命理论', type: 'document', status: 'done' },
            { id: 'sum-06', title: '第七节纪要·新民主主义革命三大法宝', type: 'document', status: 'done' },
            { id: 'sum-07', title: '第八节纪要·社会主义改造理论（上）', type: 'document', status: 'done' },
            { id: 'sum-08', title: '第九节纪要·社会主义改造理论（下）', type: 'document', status: 'done' },
            { id: 'sum-09', title: '第十二节纪要·毛泽东思想活的灵魂', type: 'document', status: 'done' },
            { id: 'sum-10', title: '第十四节纪要·邓小平理论', type: 'document', status: 'done' },
            { id: 'sum-11', title: '第十五节纪要·一国两制与祖国统一', type: 'document', status: 'done' },
            { id: 'sum-12', title: '补充课纪要·期末复习', type: 'document', status: 'done' },
          ],
        },
        ...examPlaceholderCategories,
      ],
    },
    {
      id: 'other',
      name: '其他',
      icon: 'FolderOpen',
      categories: [
        {
          id: 'english',
          name: '英语练习',
          items: [
            { id: 'unit-1', title: '大学英语 Unit 1 · The True Value of Education', type: 'document', status: 'done' },
            { id: 'unit-2', title: '大学英语 Unit 2 · The Myth of a Dream Job', type: 'document', status: 'done' },
            { id: 'unit-3', title: '大学英语 Unit 3 · The Business of Life', type: 'document', status: 'done' },
            { id: 'unit-4', title: '大学英语 Unit 4 · Explore the Unknown', type: 'document', status: 'done' },
            { id: 'unit-5', title: '大学英语 Unit 5 · The Power of Language', type: 'document', status: 'done' },
            { id: 'unit-6', title: '大学英语 Unit 6 · Technology and Human Connection', type: 'document', status: 'done' },
            { id: 'unit-7', title: '大学英语 Unit 7 · The Art of Innovation', type: 'document', status: 'done' },
            { id: 'unit-8', title: '大学英语 Unit 8 · Nature and Human Society', type: 'document', status: 'done' },
          ],
        },
        {
          id: 'misc',
          name: '工具',
          items: [
            { id: 'exam-source', title: '历届真题资源包', type: 'document', status: 'done', renderType: 'html' },
          ],
        },
        {
          id: 'gongshi',
          name: '公式',
          items: [
            { id: 'gongshi', title: '概率论公式', type: 'document', status: 'done', renderType: 'html' },
          ],
        },
        {
          id: 'guihua',
          name: '规划',
          items: [
            { id: 'schedule', title: '复习计划', type: 'document', status: 'done', renderType: 'html' },
          ],
        },
      ],
    },
  ],
};

/**
 * @deprecated 仅覆盖概率论 detail 分类。新代码应直接使用 contentTree。
 * 保留此导出供页面路由等旧消费方兼容。
 */
export const manifest = {
  course: '概率论与数理统计',
  chapters: contentTree.subjects[0].categories[1].items.map((ch) => ({
    id: ch.id,
    number: parseInt(ch.id.replace('ch', '')),
    title: ch.title,
    summary: ch.summary || '',
    sections: (ch.children || []).map((sec) => ({
      id: sec.id,
      title: sec.title,
      summary: sec.summary || '',
      status: sec.status || 'stub',
      videoIds: sec.videoIds || [],
      interactiveIds: sec.interactiveIds || [],
    })),
    recordings: probabilityRecordings[ch.id] || [],
  })),
};

export default manifest;
