import type { ContentItem } from '@/lib/types/content';

/**
 * 概率论与数理统计 · 详解分类内容
 * 8 章完整数据，每章含 sections、summary、videoIds、interactiveIds。
 */
export const probabilityDetailItems: ContentItem[] = [
  {
    id: 'ch01',
    title: '随机事件与概率',
    type: 'section',
    status: 'done',
    summary:
      '随机试验、样本空间与随机事件；事件的关系与运算；频率与概率的公理化定义；古典概型与几何概型；条件概率、乘法公式、全概率公式与贝叶斯公式；事件的独立性。',
    children: [
      {
        id: '1.1',
        title: '随机试验与样本空间',
        type: 'section',
        status: 'done',
        summary: '随机现象与确定现象的区别；随机试验的三大特征；样本点、样本空间与随机事件的集合化描述。',
        videoIds: ['ch01-1.1-sample-space'],
        interactiveIds: ['ch01-1.1-events'],
      },
      {
        id: '1.2',
        title: '事件间的关系与运算',
        type: 'section',
        status: 'done',
        summary: '包含、相等、和、积、差、互斥、对立；事件运算律与德摩根定律；用集合语言刻画事件。',
        videoIds: ['ch01-1.2-ops'],
        interactiveIds: ['ch01-1.2-venn'],
      },
      {
        id: '1.3',
        title: '频率与概率',
        type: 'section',
        status: 'done',
        summary: '频率的统计稳定性；概率的统计定义与公理化定义；概率的基本性质与推论。',
        videoIds: ['ch01-1.3-freq'],
        interactiveIds: ['ch01-1.3-frequency'],
      },
      {
        id: '1.4',
        title: '古典概型与几何概型',
        type: 'section',
        status: 'done',
        summary: '等可能概型的计算框架；排列组合计数；几何概型与测度比；经典摸球、分配、会面问题。',
        videoIds: ['ch01-1.4-classical'],
        interactiveIds: ['ch01-1.4-coins'],
      },
      {
        id: '1.5',
        title: '条件概率·乘法公式·全概率与贝叶斯公式',
        type: 'section',
        status: 'done',
        summary: '条件概率定义与直觉；乘法公式；划分与全概率公式；贝叶斯公式与先验/后验思想。',
        videoIds: ['ch01-1.5-bayes'],
        interactiveIds: ['ch01-1.5-bayes-lab'],
      },
      {
        id: '1.6',
        title: '事件的独立性',
        type: 'section',
        status: 'done',
        summary: '两事件独立的定义与判定；多事件相互独立与两两独立的区别；独立性在可靠性问题中的应用。',
        videoIds: ['ch01-1.6-indep'],
        interactiveIds: ['ch01-1.6-reliability'],
      },
    ],
  },
  {
    id: 'ch02',
    title: '随机变量及其分布',
    type: 'section',
    status: 'done',
    summary: '随机变量概念；离散型分布与分布律；连续型分布与概率密度；分布函数；常见分布；随机变量函数的分布。',
    children: [
      {
        id: '2.1',
        title: '随机变量的概念',
        type: 'section',
        status: 'done',
        summary: '随机变量的直觉与定义（样本空间到实数轴的映射）；离散与连续随机变量的区分；为什么需要引入随机变量。',
        videoIds: ['ch02-2.1-rv-concept'],
        interactiveIds: ['ch02-2.1-rv-mapper'],
      },
      {
        id: '2.2',
        title: '离散型随机变量与常见分布',
        type: 'section',
        status: 'done',
        summary: '分布律的定义与性质；两点分布；二项分布 B(n,p)；泊松分布 P(λ)；泊松定理（二项逼近泊松）。',
        videoIds: ['ch02-2.2-discrete-dist'],
        interactiveIds: ['ch02-2.2-binomial-explorer'],
      },
      {
        id: '2.3',
        title: '随机变量的分布函数',
        type: 'section',
        status: 'done',
        summary: '分布函数 F(x)=P(X≤x) 的定义；右连续性、单调不减、极限条件；离散型与连续型的 F(x) 图像；用 F(x) 计算区间概率。',
        videoIds: ['ch02-2.3-cdf'],
        interactiveIds: ['ch02-2.3-cdf-visualizer'],
      },
      {
        id: '2.4',
        title: '连续型随机变量与常见连续分布',
        type: 'section',
        status: 'done',
        summary: '概率密度函数 f(x) 的定义与性质；均匀分布 U(a,b)；指数分布 Exp(λ) 与无记忆性；正态分布 N(μ,σ²) 与标准化；3σ规则。',
        videoIds: ['ch02-2.4-continuous-dist'],
        interactiveIds: ['ch02-2.4-pdf-explorer'],
      },
      {
        id: '2.5',
        title: '随机变量函数的分布',
        type: 'section',
        status: 'done',
        summary: '已知 X 的分布，求 Y=g(X) 的分布；分布函数法（连续型）；单调函数的公式法；离散型直接列表法；典型例题：Y=X²、Y=e^X、Y=aX+b。',
        videoIds: ['ch02-2.5-func-dist'],
        interactiveIds: ['ch02-2.5-func-dist-demo'],
      },
    ],
  },
  {
    id: 'ch03',
    title: '多维随机变量及其分布',
    type: 'section',
    status: 'done',
    summary: '二维分布函数与联合/边缘分布；条件分布；相互独立性；多维随机变量函数的分布。',
    children: [
      {
        id: '3.1',
        title: '二维随机变量与联合分布',
        type: 'section',
        status: 'done',
        summary: '二维随机变量 (X,Y) 的概念；联合分布函数 F(x,y)=P(X≤x,Y≤y) 的定义与性质；离散型联合分布律；连续型联合概率密度 f(x,y)。',
        videoIds: ['ch03-3.1-joint-dist'],
        interactiveIds: ['ch03-3.1-joint-dist-explorer'],
      },
      {
        id: '3.2',
        title: '边缘分布',
        type: 'section',
        status: 'done',
        summary: '边缘分布律/密度的定义（对另一变量求和/积分）；边缘 CDF 与联合 CDF 的关系；联合分布确定边缘分布但反过来不成立（说明独立性重要性）。',
        videoIds: ['ch03-3.2-marginal-dist'],
        interactiveIds: ['ch03-3.2-marginal-explorer'],
      },
      {
        id: '3.3',
        title: '条件分布',
        type: 'section',
        status: 'done',
        summary: '离散型条件分布律 P(X=xi|Y=yj)=p(xi,yj)/pj；连续型条件密度 f_{X|Y}(x|y)=f(x,y)/f_Y(y)；条件分布与联合分布的几何关系；条件期望的概念引入。',
        videoIds: ['ch03-3.3-conditional-dist'],
        interactiveIds: ['ch03-3.3-conditional-explorer'],
      },
      {
        id: '3.4',
        title: '随机变量的独立性',
        type: 'section',
        status: 'done',
        summary: '两个随机变量相互独立的定义：F(x,y)=F_X(x)F_Y(y) 等价于 f(x,y)=f_X(x)f_Y(y)（连续）或 p(xi,yj)=pi·qj（离散）；独立的充要条件；独立与不相关的关系（独立⟹不相关，反之不然）。',
        videoIds: ['ch03-3.4-rv-independence'],
        interactiveIds: ['ch03-3.4-independence-checker'],
      },
      {
        id: '3.5',
        title: '两个随机变量函数的分布',
        type: 'section',
        status: 'done',
        summary: 'Z=X+Y 的分布（卷积公式）；正态分布的可加性；Z=max(X,Y) 和 Z=min(X,Y) 的分布；一般函数的分布函数法。',
        videoIds: ['ch03-3.5-sum-dist'],
        interactiveIds: ['ch03-3.5-convolution-demo'],
      },
    ],
  },
  {
    id: 'ch04',
    title: '随机变量的数字特征',
    type: 'section',
    status: 'done',
    summary: '数学期望与方差；协方差与相关系数；矩与协方差矩阵。',
    children: [
      {
        id: '4.1',
        title: '数学期望',
        type: 'section',
        status: 'done',
        summary: '离散型期望 E[X]=Σxi·pi；连续型期望 E[X]=∫x·f(x)dx；随机变量函数的期望 E[g(X)]；期望的线性性质；常见分布的期望。',
        videoIds: ['ch04-4.1-expectation'],
        interactiveIds: ['ch04-4.1-expectation-explorer'],
      },
      {
        id: '4.2',
        title: '方差与标准差',
        type: 'section',
        status: 'done',
        summary: '方差 D(X)=E[(X-μ)²] 的定义；计算公式 D(X)=E[X²]-(E[X])²；方差的性质（线性变换）；标准差与标准化；常见分布的方差。',
        videoIds: ['ch04-4.2-variance'],
        interactiveIds: ['ch04-4.2-variance-explorer'],
      },
      {
        id: '4.3',
        title: '协方差与相关系数',
        type: 'section',
        status: 'done',
        summary: '协方差 Cov(X,Y)=E[(X-μX)(Y-μY)]；计算简化公式；相关系数 ρ∈[-1,1]；ρ=0（不相关）vs 独立；不相关不一定独立的反例；二维正态的特殊性。',
        videoIds: ['ch04-4.3-covariance'],
        interactiveIds: ['ch04-4.3-correlation-explorer'],
      },
      {
        id: '4.4',
        title: '矩与协方差矩阵',
        type: 'section',
        status: 'done',
        summary: 'k阶原点矩 E[X^k]、k阶中心矩 E[(X-μ)^k]；偏度与峰度（简介）；二维协方差矩阵 Σ；协方差矩阵的几何意义（椭圆方程）；多维正态分布简介。',
        videoIds: ['ch04-4.4-moments'],
        interactiveIds: ['ch04-4.4-cov-matrix-demo'],
      },
    ],
  },
  {
    id: 'ch05',
    title: '大数定律与中心极限定理',
    type: 'section',
    status: 'done',
    summary: '切比雪夫不等式；大数定律；中心极限定理及其应用。',
    children: [
      {
        id: '5.1',
        title: '切比雪夫不等式',
        type: 'section',
        status: 'done',
        summary: '切比雪夫不等式 P(|X-μ|≥ε)≤σ²/ε²；由方差上界推偏离概率上界；用途：在不知分布具体形式时给出概率界；与大数定律的关系（用不等式证明大数定律）。',
        videoIds: ['ch05-5.1-chebyshev'],
        interactiveIds: ['ch05-5.1-chebyshev-demo'],
      },
      {
        id: '5.2',
        title: '大数定律',
        type: 'section',
        status: 'done',
        summary: '依概率收敛的定义；伯努利大数定律（频率稳定于概率）；辛钦大数定律（样本均值稳定于总体均值）；大数定律的统计意义：为统计推断奠基。',
        videoIds: ['ch05-5.2-lln'],
        interactiveIds: ['ch05-5.2-lln-simulator'],
      },
      {
        id: '5.3',
        title: '中心极限定理',
        type: 'section',
        status: 'done',
        summary: '林德伯格-莱维中心极限定理：i.i.d.、有限方差时 √n(X̄n-μ)/σ → N(0,1)；实用形式：X̄n 近似 N(μ,σ²/n)，ΣXi 近似 N(nμ,nσ²)；棣莫弗-拉普拉斯定理；正态近似的使用条件与例题。',
        videoIds: ['ch05-5.3-clt'],
        interactiveIds: ['ch05-5.3-clt-simulator'],
      },
    ],
  },
  {
    id: 'ch06',
    title: '样本及抽样分布',
    type: 'section',
    status: 'done',
    summary: '总体与样本；统计量；χ²、t、F 分布；正态总体的抽样分布定理。',
    children: [
      {
        id: '6.1',
        title: '总体、样本与统计量',
        type: 'section',
        status: 'done',
        summary: '总体（随机变量）与个体；简单随机样本（i.i.d.）；统计量的定义（不含未知参数的样本函数）；样本均值 X̄、样本方差 S²（分母 n-1 原因）、样本标准差 S；为什么用 n-1（无偏性）。',
        videoIds: ['ch06-6.1-population-sample'],
        interactiveIds: ['ch06-6.1-statistic-calculator'],
      },
      {
        id: '6.2',
        title: '三大抽样分布',
        type: 'section',
        status: 'done',
        summary: 'χ²(n) 分布（n 个独立标准正态平方和）；t(n) 分布（X/√(χ²/n) 的结构与对称性）；F(m,n) 分布（两χ²之比）；各分布的 PDF 形状与自由度的影响；临界值的使用。',
        videoIds: ['ch06-6.2-sampling-dist'],
        interactiveIds: ['ch06-6.2-sampling-dist-explorer'],
      },
      {
        id: '6.3',
        title: '正态总体的抽样分布定理',
        type: 'section',
        status: 'done',
        summary: 'X~N(μ,σ²) 时：X̄~N(μ,σ²/n)；(n-1)S²/σ²~χ²(n-1)；X̄与S²相互独立（正态总体独有性质）；(X̄-μ)/(S/√n)~t(n-1)；这四个结论是区间估计和假设检验的基石。',
        videoIds: ['ch06-6.3-normal-sampling'],
        interactiveIds: ['ch06-6.3-normal-sampling-demo'],
      },
      {
        id: '6.4',
        title: '样本分位数与顺序统计量',
        type: 'section',
        status: 'done',
        summary: '顺序统计量 X(1)≤X(2)≤…≤X(n) 的概念；最小/最大值分布；样本中位数；分位数的概念与实际应用（Q-Q图直觉）；与参数估计的联系。',
        videoIds: ['ch06-6.4-order-stat'],
        interactiveIds: ['ch06-6.4-quantile-explorer'],
      },
    ],
  },
  {
    id: 'ch07',
    title: '参数估计',
    type: 'section',
    status: 'done',
    summary: '矩估计与极大似然估计；估计量的评选标准；区间估计。',
    children: [
      {
        id: '7.1',
        title: '矩估计法',
        type: 'section',
        status: 'done',
        summary: '替换原理：用样本矩替换总体矩；一阶矩（均值）→估计 μ 或 λ 等；二阶矩→估计 σ²；以指数分布、均匀分布为例写出矩估计量的完整推导过程。',
        videoIds: ['ch07-7.1-moment-est'],
        interactiveIds: ['ch07-7.1-moment-estimator'],
      },
      {
        id: '7.2',
        title: '最大似然估计',
        type: 'section',
        status: 'done',
        summary: '似然函数 L(θ) 的定义与直觉（给定数据，θ 多大时数据最可能出现）；对数似然；MLE 的求解步骤（令对数似然导数=0）；以二项/正态/指数为例；MLE 的不变性原理。',
        videoIds: ['ch07-7.2-mle'],
        interactiveIds: ['ch07-7.2-mle-explorer'],
      },
      {
        id: '7.3',
        title: '估计量的评选标准',
        type: 'section',
        status: 'done',
        summary: '无偏性（E[θ̂]=θ）；有效性（方差最小，CR 下界）；相合性（θ̂→θ，n→∞）；以样本均值 vs (n-1)S² vs nS² 的方差为例；渐近正态性；估计量的均方误差 MSE=偏差²+方差。',
        videoIds: ['ch07-7.3-estimator-quality'],
        interactiveIds: ['ch07-7.3-estimator-comparator'],
      },
      {
        id: '7.4',
        title: '区间估计',
        type: 'section',
        status: 'done',
        summary: '点估计 vs 区间估计；置信区间 (L,U) 的定义 P(L≤θ≤U)=1-α；置信水平 1-α；枢轴量法；正态总体 μ 的置信区间（σ已知用 Z，σ未知用 t）；正态总体 σ² 的置信区间（χ²分布）；区间长度与样本量的关系。',
        videoIds: ['ch07-7.4-conf-interval'],
        interactiveIds: ['ch07-7.4-conf-interval-explorer'],
      },
    ],
  },
  {
    id: 'ch08',
    title: '假设检验',
    type: 'section',
    status: 'done',
    summary: '假设检验的基本思想；正态总体均值与方差的检验；两类错误。',
    children: [
      {
        id: '8.1',
        title: '假设检验的基本思想',
        type: 'section',
        status: 'done',
        summary: '原假设 H0 与备择假设 H1；小概率原理（α=0.05 时小概率事件若发生则拒绝 H0）；检验统计量与拒绝域；显著性水平 α 的含义；第一类错误（弃真）vs 第二类错误（纳伪）；假设检验的决策逻辑。',
        videoIds: ['ch08-8.1-hyp-test-intro'],
        interactiveIds: ['ch08-8.1-hyp-test-demo'],
      },
      {
        id: '8.2',
        title: '正态总体均值的假设检验',
        type: 'section',
        status: 'done',
        summary: 'σ²已知时的 Z 检验（统计量 Z=(X̄-μ0)/(σ/√n)）；σ²未知时的 t 检验（统计量 T=(X̄-μ0)/(S/√n)，t(n-1)分布）；双边检验与单边检验；两个正态总体均值之差的检验；检验的步骤与例题。',
        videoIds: ['ch08-8.2-mean-test'],
        interactiveIds: ['ch08-8.2-mean-test-explorer'],
      },
      {
        id: '8.3',
        title: '正态总体方差的假设检验',
        type: 'section',
        status: 'done',
        summary: '单个正态总体方差的 χ² 检验（统计量 χ²=(n-1)S²/σ0²）；两个正态总体方差比的 F 检验；检验的拒绝域；单/双侧检验；例题与实际应用（质量控制）。',
        videoIds: ['ch08-8.3-variance-test'],
        interactiveIds: ['ch08-8.3-variance-test-explorer'],
      },
      {
        id: '8.4',
        title: '两类错误与检验功效',
        type: 'section',
        status: 'done',
        summary: '第一类错误（弃真，概率=α）vs 第二类错误（纳伪，概率=β）；α 与 β 的权衡；势函数 W(θ) = P(拒绝H0|θ)；功效 = 1-β；样本量对两类错误的影响；最优检验简介；假设检验的局限与 p 值的正确解读。',
        videoIds: ['ch08-8.4-two-errors'],
        interactiveIds: ['ch08-8.4-error-type-demo'],
      },
    ],
  },
];

/** 各章录音文件映射（保留原始 recordings 数据，供兼容导出使用） */
export const probabilityRecordings: Record<string, string[]> = {
  ch01: [
    '概率论与数理统计-第一节.txt',
    '概率论-第二节.txt',
    '概率论-第三节.txt',
    '概率论-第四节.txt',
  ],
  ch02: ['概率论-第7节.txt', '概率论-第8节.txt'],
  ch03: ['概率论-第九节.txt', '概率论第十节多维随机变量分布讲解.txt', '概率论第十一节.txt', '概率论第十二节.txt'],
  ch04: ['概率论第13节 随机变量期望方差性质讲解.txt', '概率论第14节 相关系数与大数定律讲解.txt'],
  ch05: ['概率论第15节 概率论数理统计.txt'],
  ch06: ['概率论第16节 统计课程之样本与分布讲解.txt', '概率论-第17节.txt'],
  ch07: [],
  ch08: [],
};
