"use client";
import {useEffect,useState} from 'react';
import {redirectAccount} from '@/lib/auth/account';
export default function ChallengePage(){
 const [factors,setFactors]=useState<Array<{id:string;name:string}>>([]);const [factor,setFactor]=useState('');const [code,setCode]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let active=true;void fetch('/api/account/mfa',{credentials:'include'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);if(active){setFactors(body.factors);setFactor(body.factors[0]?.id||'');}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'无法读取验证器');});return()=>{active=false;};},[]);
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{
  const send=async(body:object)=>{const response=await fetch('/api/account/mfa',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'验证失败');return data;};
  const challenge=await send({action:'challenge',factorId:factor});const result=await send({action:'verify',factorId:factor,challengeId:challenge.id,code});
  window.location.assign(typeof result.next==='string'&&result.next.startsWith('/')&&!result.next.startsWith('//')?result.next:'/');
 }catch(e){setError(e instanceof Error?e.message:'验证失败');}finally{setBusy(false);}}
 return <main className="flex min-h-[70vh] items-center justify-center p-6"><section className="w-full max-w-md space-y-5 rounded-2xl border border-[var(--line)] bg-[var(--bg-panel)] p-8"><p className="text-xs uppercase tracking-widest text-[var(--ink-soft)]">1037Solo · StudySolo</p><h1 className="text-2xl font-semibold">完成两步验证</h1><p className="text-sm text-[var(--ink-soft)]">统一账号已确认。为保护你的课堂、笔记和 AI 额度，请输入验证器中的当前验证码。</p><form className="space-y-4" onSubmit={submit}><label className="block text-sm">验证器<select className="mt-2 w-full rounded-lg border bg-transparent p-3" value={factor} onChange={e=>setFactor(e.target.value)}>{factors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="block text-sm">六位验证码<input className="mt-2 w-full rounded-lg border bg-transparent p-3 text-lg tracking-widest" inputMode="numeric" autoComplete="one-time-code" maxLength={6} pattern="[0-9]{6}" required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button disabled={busy||!factor} className="w-full rounded-lg bg-emerald-700 p-3 text-white">{busy?'正在验证…':'验证并继续'}</button></form>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex justify-between"><button className="text-sm underline" onClick={()=>window.location.reload()}>重新读取验证状态</button><button className="text-sm underline" onClick={()=>redirectAccount('login')}>重新登录</button></div></section></main>;
}
